import { BaseSchema } from '@adonisjs/lucid/schema'

export default class extends BaseSchema {
  async up() {
    this.schema.createTable('visit_clients', (table) => {
      table.increments('id').unsigned().primary()
      table.integer('org_id').unsigned().notNullable().references('id').inTable('organizations').onDelete('CASCADE')
      table.string('name', 150).notNullable()
      table.string('industry', 120).nullable()
      table.string('contact_person', 150).nullable()
      table.string('email', 255).nullable()
      table.string('phone', 50).nullable()
      table.text('address').nullable()
      table.boolean('is_active').notNullable().defaultTo(true)
      table.timestamp('created_at').notNullable().defaultTo(this.now())
      table.timestamp('updated_at').nullable()
      table.unique(['org_id', 'name'])
    })

    this.schema.createTable('visit_visitors', (table) => {
      table.increments('id').unsigned().primary()
      table.integer('org_id').unsigned().notNullable().references('id').inTable('organizations').onDelete('CASCADE')
      table.integer('client_id').unsigned().nullable().references('id').inTable('visit_clients').onDelete('SET NULL')
      table.string('full_name', 150).notNullable()
      table.string('email', 255).nullable()
      table.string('phone', 50).nullable()
      table.string('designation', 150).nullable()
      table.text('address').nullable()
      table.text('notes').nullable()
      table.boolean('is_active').notNullable().defaultTo(true)
      table.timestamp('created_at').notNullable().defaultTo(this.now())
      table.timestamp('updated_at').nullable()
      table.index(['org_id', 'full_name'])
    })

    this.schema.createTable('visits', (table) => {
      table.increments('id').unsigned().primary()
      table.integer('org_id').unsigned().notNullable().references('id').inTable('organizations').onDelete('CASCADE')
      table.integer('client_id').unsigned().nullable().references('id').inTable('visit_clients').onDelete('SET NULL')
      table.integer('visitor_id').unsigned().nullable().references('id').inTable('visit_visitors').onDelete('SET NULL')
      table.integer('host_employee_id').unsigned().nullable().references('id').inTable('employees').onDelete('SET NULL')
      table.integer('created_by').unsigned().notNullable().references('id').inTable('employees').onDelete('CASCADE')
      table.integer('approver_employee_id').unsigned().nullable().references('id').inTable('employees').onDelete('SET NULL')
      table.integer('approved_by').unsigned().nullable().references('id').inTable('employees').onDelete('SET NULL')
      table.string('title', 180).notNullable()
      table.text('purpose').notNullable()
      table.string('location_name', 180).nullable()
      table.string('visit_type', 50).notNullable().defaultTo('client_meeting')
      table.string('priority', 30).notNullable().defaultTo('medium')
      table.string('status', 40).notNullable().defaultTo('planned')
      table.boolean('requires_approval').notNullable().defaultTo(false)
      table.timestamp('scheduled_start').notNullable()
      table.timestamp('scheduled_end').nullable()
      table.timestamp('reminder_at').nullable()
      table.timestamp('approved_at').nullable()
      table.timestamp('actual_check_in_at').nullable()
      table.timestamp('actual_check_out_at').nullable()
      table.decimal('check_in_latitude', 10, 7).nullable()
      table.decimal('check_in_longitude', 10, 7).nullable()
      table.decimal('check_out_latitude', 10, 7).nullable()
      table.decimal('check_out_longitude', 10, 7).nullable()
      table.text('check_in_address').nullable()
      table.text('check_out_address').nullable()
      table.text('photo_proof_url').nullable()
      table.text('attachment_urls').nullable()
      table.text('approval_notes').nullable()
      table.text('completion_notes').nullable()
      table.timestamp('created_at').notNullable().defaultTo(this.now())
      table.timestamp('updated_at').nullable()
      table.index(['org_id', 'status'])
      table.index(['org_id', 'scheduled_start'])
    })

    this.schema.createTable('visit_notes', (table) => {
      table.increments('id').unsigned().primary()
      table.integer('visit_id').unsigned().notNullable().references('id').inTable('visits').onDelete('CASCADE')
      table.integer('org_id').unsigned().notNullable().references('id').inTable('organizations').onDelete('CASCADE')
      table.integer('employee_id').unsigned().nullable().references('id').inTable('employees').onDelete('SET NULL')
      table.string('note_type', 50).notNullable().defaultTo('general')
      table.text('content').notNullable()
      table.text('attachment_urls').nullable()
      table.text('photo_proof_url').nullable()
      table.timestamp('created_at').notNullable().defaultTo(this.now())
      table.index(['visit_id', 'created_at'])
    })

    this.schema.createTable('visit_follow_ups', (table) => {
      table.increments('id').unsigned().primary()
      table.integer('visit_id').unsigned().notNullable().references('id').inTable('visits').onDelete('CASCADE')
      table.integer('org_id').unsigned().notNullable().references('id').inTable('organizations').onDelete('CASCADE')
      table.integer('assigned_to').unsigned().nullable().references('id').inTable('employees').onDelete('SET NULL')
      table.integer('created_by').unsigned().nullable().references('id').inTable('employees').onDelete('SET NULL')
      table.string('status', 30).notNullable().defaultTo('open')
      table.string('priority', 30).notNullable().defaultTo('medium')
      table.string('title', 180).notNullable()
      table.text('description').nullable()
      table.timestamp('due_at').nullable()
      table.timestamp('completed_at').nullable()
      table.timestamp('created_at').notNullable().defaultTo(this.now())
      table.timestamp('updated_at').nullable()
      table.index(['org_id', 'status'])
      table.index(['org_id', 'due_at'])
    })
  }

  async down() {
    this.schema.dropTable('visit_follow_ups')
    this.schema.dropTable('visit_notes')
    this.schema.dropTable('visits')
    this.schema.dropTable('visit_visitors')
    this.schema.dropTable('visit_clients')
  }
}
