/**
 * This file is automatically generated
 * DO NOT EDIT manually
 * Run "node ace migration:run" command to re-generate this file
 */

import { BaseModel, column } from '@adonisjs/lucid/orm'
import { DateTime } from 'luxon'

export class AddonPriceSchema extends BaseModel {
  static $columns = ['id', 'name', 'slug', 'description', 'price', 'planType', 'isActive', 'createdAt', 'updatedAt'] as const
  $columns = AddonPriceSchema.$columns
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare name: string
  @column()
  declare slug: string
  @column()
  declare description: string | null
  @column()
  declare price: string
  @column()
  declare planType: number | null
  @column()
  declare isActive: boolean
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class AnnouncementSchema extends BaseModel {
  static $columns = ['id', 'orgId', 'createdBy', 'title', 'content', 'target', 'targetId', 'priority', 'publishedAt', 'expiresAt', 'createdAt', 'updatedAt'] as const
  $columns = AnnouncementSchema.$columns
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare orgId: number
  @column()
  declare createdBy: number
  @column()
  declare title: string
  @column()
  declare content: string | null
  @column()
  declare target: string
  @column()
  declare targetId: number | null
  @column()
  declare priority: string | null
  @column.dateTime()
  declare publishedAt: DateTime
  @column.dateTime()
  declare expiresAt: DateTime | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class ApiRateLimitSchema extends BaseModel {
  static $columns = ['id', 'ipAddress', 'endpoint', 'hits', 'resetAt'] as const
  $columns = ApiRateLimitSchema.$columns
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare ipAddress: string
  @column()
  declare endpoint: string | null
  @column()
  declare hits: number | null
  @column.dateTime()
  declare resetAt: DateTime | null
}

export class AttendanceSchema extends BaseModel {
  static $columns = ['id', 'employeeId', 'orgId', 'shiftId', 'attendanceDate', 'checkIn', 'checkOut', 'workHours', 'checkInLat', 'checkInLng', 'checkOutLat', 'checkOutLng', 'deviceInfo', 'selfieUrl', 'biometricRef', 'status', 'isLate', 'isHalfDay', 'isOvertime', 'totalBreakMin', 'netWorkHours', 'source', 'notes', 'modifiedBy', 'modifiedAt', 'createdAt'] as const
  $columns = AttendanceSchema.$columns
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare employeeId: number
  @column()
  declare orgId: number
  @column()
  declare shiftId: number | null
  @column.date()
  declare attendanceDate: DateTime
  @column.dateTime()
  declare checkIn: DateTime | null
  @column.dateTime()
  declare checkOut: DateTime | null
  @column()
  declare workHours: string | null
  @column()
  declare checkInLat: string | null
  @column()
  declare checkInLng: string | null
  @column()
  declare checkOutLat: string | null
  @column()
  declare checkOutLng: string | null
  @column()
  declare deviceInfo: string | null
  @column()
  declare selfieUrl: string | null
  @column()
  declare biometricRef: string | null
  @column()
  declare status: string | null
  @column()
  declare isLate: boolean | null
  @column()
  declare isHalfDay: boolean | null
  @column()
  declare isOvertime: boolean | null
  @column()
  declare totalBreakMin: number | null
  @column()
  declare netWorkHours: string | null
  @column()
  declare source: string | null
  @column()
  declare notes: string | null
  @column()
  declare modifiedBy: number | null
  @column.dateTime()
  declare modifiedAt: DateTime | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
}

export class AttendanceBreakSchema extends BaseModel {
  static $columns = ['id', 'attendanceId', 'employeeId', 'breakStart', 'breakEnd', 'breakDurationMin', 'createdAt'] as const
  $columns = AttendanceBreakSchema.$columns
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare attendanceId: number
  @column()
  declare employeeId: number
  @column.dateTime()
  declare breakStart: DateTime
  @column.dateTime()
  declare breakEnd: DateTime | null
  @column()
  declare breakDurationMin: number | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
}

export class AttendanceRegularizationSchema extends BaseModel {
  static $columns = ['id', 'employeeId', 'orgId', 'attendanceId', 'regularizationDate', 'type', 'reason', 'status', 'adminNotes', 'approvedBy', 'approvedAt', 'createdAt'] as const
  $columns = AttendanceRegularizationSchema.$columns
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare employeeId: number
  @column()
  declare orgId: number
  @column()
  declare attendanceId: number | null
  @column.date()
  declare regularizationDate: DateTime
  @column()
  declare type: string
  @column()
  declare reason: string
  @column()
  declare status: string | null
  @column()
  declare adminNotes: string | null
  @column()
  declare approvedBy: number | null
  @column.dateTime()
  declare approvedAt: DateTime | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
}

export class AttendanceRequestSchema extends BaseModel {
  static $columns = ['id', 'employeeId', 'orgId', 'requestType', 'requestedTime', 'reason', 'status', 'approvedBy', 'approvedAt', 'createdAt'] as const
  $columns = AttendanceRequestSchema.$columns
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare employeeId: number
  @column()
  declare orgId: number
  @column()
  declare requestType: string
  @column.dateTime()
  declare requestedTime: DateTime
  @column()
  declare reason: string
  @column()
  declare status: string | null
  @column()
  declare approvedBy: number | null
  @column.dateTime()
  declare approvedAt: DateTime | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
}

export class AuditLogSchema extends BaseModel {
  static $columns = ['id', 'orgId', 'employeeId', 'action', 'module', 'entityName', 'entityId', 'oldValues', 'newValues', 'ipAddress', 'userAgent', 'isImmutable', 'createdAt'] as const
  $columns = AuditLogSchema.$columns
  @column({ isPrimary: true })
  declare id: bigint | number
  @column()
  declare orgId: number | null
  @column()
  declare employeeId: number | null
  @column()
  declare action: string
  @column()
  declare module: string
  @column()
  declare entityName: string | null
  @column()
  declare entityId: string | null
  @column()
  declare oldValues: string | null
  @column()
  declare newValues: string | null
  @column()
  declare ipAddress: string | null
  @column()
  declare userAgent: string | null
  @column()
  declare isImmutable: boolean
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
}

export class AuthAccessTokenSchema extends BaseModel {
  static $columns = ['id', 'tokenableId', 'type', 'name', 'hash', 'abilities', 'lastUsedAt', 'expiresAt', 'createdAt', 'updatedAt'] as const
  $columns = AuthAccessTokenSchema.$columns
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare tokenableId: number
  @column()
  declare type: string
  @column()
  declare name: string | null
  @column()
  declare hash: string
  @column()
  declare abilities: string
  @column.dateTime()
  declare lastUsedAt: DateTime | null
  @column.dateTime()
  declare expiresAt: DateTime | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class DataErasureRequestSchema extends BaseModel {
  static $columns = ['id', 'employeeId', 'orgId', 'reason', 'status', 'createdAt'] as const
  $columns = DataErasureRequestSchema.$columns
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare employeeId: number
  @column()
  declare orgId: number
  @column()
  declare reason: string | null
  @column()
  declare status: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
}

export class DepartmentSchema extends BaseModel {
  static $columns = ['id', 'orgId', 'parentId', 'departmentName', 'description', 'isActive', 'deletedAt', 'createdAt', 'updatedAt'] as const
  $columns = DepartmentSchema.$columns
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare orgId: number
  @column()
  declare parentId: number | null
  @column()
  declare departmentName: string
  @column()
  declare description: string | null
  @column()
  declare isActive: boolean
  @column.dateTime()
  declare deletedAt: DateTime | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class DesignationSchema extends BaseModel {
  static $columns = ['id', 'orgId', 'departmentId', 'designationName', 'createdAt', 'updatedAt'] as const
  $columns = DesignationSchema.$columns
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare orgId: number
  @column()
  declare departmentId: number | null
  @column()
  declare designationName: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class DocumentSchema extends BaseModel {
  static $columns = ['id', 'orgId', 'employeeId', 'fileName', 'filePath', 'fileType', 'fileSize', 'category', 'isPublic', 'createdAt'] as const
  $columns = DocumentSchema.$columns
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare orgId: number
  @column()
  declare employeeId: number
  @column()
  declare fileName: string
  @column()
  declare filePath: string
  @column()
  declare fileType: string | null
  @column()
  declare fileSize: number | null
  @column()
  declare category: string | null
  @column()
  declare isPublic: boolean | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
}

export class DocumentAccessLogSchema extends BaseModel {
  static $columns = ['id', 'docId', 'employeeId', 'action', 'ipAddress', 'accessedAt'] as const
  $columns = DocumentAccessLogSchema.$columns
  @column({ isPrimary: true })
  declare id: bigint | number
  @column()
  declare docId: number
  @column()
  declare employeeId: number
  @column()
  declare action: string
  @column()
  declare ipAddress: string | null
  @column.dateTime()
  declare accessedAt: DateTime
}

export class EmailVerificationTokenSchema extends BaseModel {
  static $columns = ['id', 'employeeId', 'orgId', 'email', 'token', 'tokenHash', 'purpose', 'isUsed', 'usedAt', 'expiresAt', 'ipAddress', 'createdAt'] as const
  $columns = EmailVerificationTokenSchema.$columns
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare employeeId: number | null
  @column()
  declare orgId: number | null
  @column()
  declare email: string
  @column()
  declare token: string
  @column()
  declare tokenHash: string
  @column()
  declare purpose: string
  @column()
  declare isUsed: boolean
  @column.dateTime()
  declare usedAt: DateTime | null
  @column.dateTime()
  declare expiresAt: DateTime
  @column()
  declare ipAddress: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
}

export class EmployeeSchema extends BaseModel {
  static $columns = ['id', 'orgId', 'departmentId', 'designationId', 'roleId', 'managerId', 'employeeCode', 'firstName', 'lastName', 'email', 'phone', 'passwordHash', 'mustChangePassword', 'isLocked', 'lockedUntil', 'avatar', 'gender', 'dateOfBirth', 'address', 'emergencyContact', 'emergencyPhone', 'salary', 'bankAccount', 'bankName', 'ifscCode', 'panNumber', 'aadharLast4', 'joinDate', 'exitDate', 'exitReason', 'status', 'emailVerified', 'deletedAt', 'deletedBy', 'createdAt', 'updatedAt'] as const
  $columns = EmployeeSchema.$columns
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare orgId: number
  @column()
  declare departmentId: number | null
  @column()
  declare designationId: number | null
  @column()
  declare roleId: number | null
  @column()
  declare managerId: number | null
  @column()
  declare employeeCode: string | null
  @column()
  declare firstName: string
  @column()
  declare lastName: string | null
  @column()
  declare email: string | null
  @column()
  declare phone: string | null
  @column()
  declare passwordHash: string | null
  @column()
  declare mustChangePassword: boolean
  @column()
  declare isLocked: boolean
  @column.dateTime()
  declare lockedUntil: DateTime | null
  @column()
  declare avatar: string | null
  @column()
  declare gender: string | null
  @column.date()
  declare dateOfBirth: DateTime | null
  @column()
  declare address: string | null
  @column()
  declare emergencyContact: string | null
  @column()
  declare emergencyPhone: string | null
  @column()
  declare salary: string
  @column()
  declare bankAccount: string | null
  @column()
  declare bankName: string | null
  @column()
  declare ifscCode: string | null
  @column()
  declare panNumber: string | null
  @column()
  declare aadharLast4: string | null
  @column.date()
  declare joinDate: DateTime | null
  @column.date()
  declare exitDate: DateTime | null
  @column()
  declare exitReason: string | null
  @column()
  declare status: string
  @column()
  declare emailVerified: boolean
  @column.dateTime()
  declare deletedAt: DateTime | null
  @column()
  declare deletedBy: number | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class EmployeeInvitationSchema extends BaseModel {
  static $columns = ['id', 'orgId', 'email', 'token', 'roleId', 'status', 'expiresAt', 'invitedBy', 'createdAt'] as const
  $columns = EmployeeInvitationSchema.$columns
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare orgId: number
  @column()
  declare email: string
  @column()
  declare token: string
  @column()
  declare roleId: number | null
  @column()
  declare status: string
  @column.dateTime()
  declare expiresAt: DateTime
  @column()
  declare invitedBy: number | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
}

export class EmployeeLocationSchema extends BaseModel {
  static $columns = ['id', 'employeeId', 'orgId', 'latitude', 'longitude', 'capturedAt'] as const
  $columns = EmployeeLocationSchema.$columns
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare employeeId: number
  @column()
  declare orgId: number
  @column()
  declare latitude: string
  @column()
  declare longitude: string
  @column.dateTime()
  declare capturedAt: DateTime
}

export class EmployeeShiftSchema extends BaseModel {
  static $columns = ['employeeId', 'shiftId', 'assignedAt'] as const
  $columns = EmployeeShiftSchema.$columns
  @column()
  declare employeeId: number
  @column()
  declare shiftId: number
  @column.dateTime()
  declare assignedAt: DateTime
}

export class ExpenseSchema extends BaseModel {
  static $columns = ['id', 'orgId', 'employeeId', 'projectId', 'category', 'amount', 'expenseDate', 'description', 'receiptUrl', 'status', 'approvedBy', 'approvedAt', 'rejectionNote', 'createdAt', 'updatedAt'] as const
  $columns = ExpenseSchema.$columns
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare orgId: number
  @column()
  declare employeeId: number
  @column()
  declare projectId: number | null
  @column()
  declare category: string
  @column()
  declare amount: string
  @column.date()
  declare expenseDate: DateTime
  @column()
  declare description: string | null
  @column()
  declare receiptUrl: string | null
  @column()
  declare status: string | null
  @column()
  declare approvedBy: number | null
  @column.dateTime()
  declare approvedAt: DateTime | null
  @column()
  declare rejectionNote: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class FaceEmbeddingSchema extends BaseModel {
  static $columns = ['id', 'employeeId', 'orgId', 'embedding', 'imageUrl', 'isActive', 'createdAt', 'updatedAt'] as const
  $columns = FaceEmbeddingSchema.$columns
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare employeeId: number
  @column()
  declare orgId: number
  @column()
  declare embedding: string
  @column()
  declare imageUrl: string | null
  @column()
  declare isActive: boolean
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class GeofenceSchema extends BaseModel {
  static $columns = ['id', 'orgId', 'name', 'latitude', 'longitude', 'radiusMeters', 'address', 'isActive', 'createdAt'] as const
  $columns = GeofenceSchema.$columns
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare orgId: number
  @column()
  declare name: string
  @column()
  declare latitude: string
  @column()
  declare longitude: string
  @column()
  declare radiusMeters: number
  @column()
  declare address: string | null
  @column()
  declare isActive: boolean
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
}

export class HolidaySchema extends BaseModel {
  static $columns = ['id', 'orgId', 'name', 'holidayDate', 'type', 'createdAt'] as const
  $columns = HolidaySchema.$columns
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare orgId: number
  @column()
  declare name: string
  @column.date()
  declare holidayDate: DateTime
  @column()
  declare type: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
}

export class InvoiceSchema extends BaseModel {
  static $columns = ['id', 'paymentId', 'orgId', 'invoiceNumber', 'subtotal', 'taxPercent', 'taxAmount', 'total', 'isVoid', 'createdAt'] as const
  $columns = InvoiceSchema.$columns
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare paymentId: number
  @column()
  declare orgId: number
  @column()
  declare invoiceNumber: string
  @column()
  declare subtotal: string
  @column()
  declare taxPercent: string | null
  @column()
  declare taxAmount: string | null
  @column()
  declare total: string | null
  @column()
  declare isVoid: boolean | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
}

export class LeafSchema extends BaseModel {
  static $columns = ['id', 'employeeId', 'orgId', 'leaveTypeId', 'startDate', 'endDate', 'totalDays', 'reason', 'supportingDoc', 'status', 'approvedBy', 'approvedAt', 'rejectionNote', 'cancelledBy', 'cancelledAt', 'createdAt', 'updatedAt'] as const
  $columns = LeafSchema.$columns
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare employeeId: number
  @column()
  declare orgId: number
  @column()
  declare leaveTypeId: number | null
  @column.date()
  declare startDate: DateTime
  @column.date()
  declare endDate: DateTime
  @column()
  declare totalDays: string | null
  @column()
  declare reason: string | null
  @column()
  declare supportingDoc: string | null
  @column()
  declare status: string | null
  @column()
  declare approvedBy: number | null
  @column.dateTime()
  declare approvedAt: DateTime | null
  @column()
  declare rejectionNote: string | null
  @column()
  declare cancelledBy: number | null
  @column.dateTime()
  declare cancelledAt: DateTime | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class LeaveBalanceSchema extends BaseModel {
  static $columns = ['id', 'employeeId', 'leaveTypeId', 'year', 'totalDays', 'usedDays', 'remainingDays', 'createdAt', 'updatedAt'] as const
  $columns = LeaveBalanceSchema.$columns
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare employeeId: number
  @column()
  declare leaveTypeId: number
  @column()
  declare year: number
  @column()
  declare totalDays: string
  @column()
  declare usedDays: string
  @column()
  declare remainingDays: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class LeaveTypeSchema extends BaseModel {
  static $columns = ['id', 'orgId', 'typeName', 'daysAllowed', 'carryForward', 'maxCarryDays', 'isPaid', 'requiresDoc', 'createdAt'] as const
  $columns = LeaveTypeSchema.$columns
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare orgId: number
  @column()
  declare typeName: string
  @column()
  declare daysAllowed: number
  @column()
  declare carryForward: boolean | null
  @column()
  declare maxCarryDays: number | null
  @column()
  declare isPaid: boolean | null
  @column()
  declare requiresDoc: boolean | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
}

export class LoginAttemptSchema extends BaseModel {
  static $columns = ['id', 'employeeId', 'orgId', 'email', 'ipAddress', 'userAgent', 'attemptType', 'status', 'failureReason', 'createdAt'] as const
  $columns = LoginAttemptSchema.$columns
  @column({ isPrimary: true })
  declare id: bigint | number
  @column()
  declare employeeId: number | null
  @column()
  declare orgId: number | null
  @column()
  declare email: string
  @column()
  declare ipAddress: string
  @column()
  declare userAgent: string | null
  @column()
  declare attemptType: string
  @column()
  declare status: string
  @column()
  declare failureReason: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
}

export class MagicLinkTokenSchema extends BaseModel {
  static $columns = ['id', 'employeeId', 'token', 'expiresAt', 'isUsed', 'createdAt'] as const
  $columns = MagicLinkTokenSchema.$columns
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare employeeId: number
  @column()
  declare token: string
  @column.dateTime()
  declare expiresAt: DateTime
  @column()
  declare isUsed: boolean
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
}

export class NotificationSchema extends BaseModel {
  static $columns = ['id', 'employeeId', 'orgId', 'title', 'message', 'isRead', 'createdAt'] as const
  $columns = NotificationSchema.$columns
  @column({ isPrimary: true })
  declare id: bigint | number
  @column()
  declare employeeId: number
  @column()
  declare orgId: number
  @column()
  declare title: string
  @column()
  declare message: string | null
  @column()
  declare isRead: boolean | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
}

export class OrganizationSchema extends BaseModel {
  static $columns = ['id', 'companyName', 'slug', 'email', 'phone', 'address', 'city', 'state', 'country', 'postalCode', 'gstin', 'logo', 'planId', 'planStatus', 'planEndDate', 'userLimit', 'isActive', 'isVerified', 'verificationToken', 'timezone', 'deletedAt', 'createdAt', 'updatedAt'] as const
  $columns = OrganizationSchema.$columns
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare companyName: string
  @column()
  declare slug: string
  @column()
  declare email: string
  @column()
  declare phone: string | null
  @column()
  declare address: string | null
  @column()
  declare city: string | null
  @column()
  declare state: string | null
  @column()
  declare country: string | null
  @column()
  declare postalCode: string | null
  @column()
  declare gstin: string | null
  @column()
  declare logo: string | null
  @column()
  declare planId: number | null
  @column()
  declare planStatus: boolean
  @column.date()
  declare planEndDate: DateTime | null
  @column()
  declare userLimit: number
  @column()
  declare isActive: boolean
  @column()
  declare isVerified: boolean
  @column()
  declare verificationToken: string | null
  @column()
  declare timezone: string
  @column.dateTime()
  declare deletedAt: DateTime | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class OrganizationAddonSchema extends BaseModel {
  static $columns = ['id', 'orgId', 'addonId', 'startDate', 'endDate', 'isActive', 'createdAt', 'updatedAt'] as const
  $columns = OrganizationAddonSchema.$columns
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare orgId: number
  @column()
  declare addonId: number
  @column.date()
  declare startDate: DateTime
  @column.date()
  declare endDate: DateTime | null
  @column()
  declare isActive: boolean
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class OrgIpWhitelistSchema extends BaseModel {
  static $columns = ['id', 'orgId', 'ipCidr', 'label', 'isActive', 'createdAt'] as const
  $columns = OrgIpWhitelistSchema.$columns
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare orgId: number
  @column()
  declare ipCidr: string
  @column()
  declare label: string | null
  @column()
  declare isActive: boolean | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
}

export class OrgRegistrationSchema extends BaseModel {
  static $columns = ['id', 'companyName', 'email', 'phone', 'country', 'adminFirstName', 'adminLastName', 'adminPasswordHash', 'planId', 'emailToken', 'emailTokenExpires', 'phoneOtpHash', 'phoneOtpExpires', 'stepCompleted', 'status', 'orgId', 'approvedAt', 'rejectionReason', 'ipAddress', 'userAgent', 'expiresAt', 'createdAt', 'updatedAt'] as const
  $columns = OrgRegistrationSchema.$columns
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare companyName: string
  @column()
  declare email: string
  @column()
  declare phone: string | null
  @column()
  declare country: string | null
  @column()
  declare adminFirstName: string | null
  @column()
  declare adminLastName: string | null
  @column()
  declare adminPasswordHash: string | null
  @column()
  declare planId: number | null
  @column()
  declare emailToken: string | null
  @column.dateTime()
  declare emailTokenExpires: DateTime | null
  @column()
  declare phoneOtpHash: string | null
  @column.dateTime()
  declare phoneOtpExpires: DateTime | null
  @column()
  declare stepCompleted: boolean
  @column()
  declare status: string
  @column()
  declare orgId: number | null
  @column.dateTime()
  declare approvedAt: DateTime | null
  @column()
  declare rejectionReason: string | null
  @column()
  declare ipAddress: string | null
  @column()
  declare userAgent: string | null
  @column.dateTime()
  declare expiresAt: DateTime
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class OtpTokenSchema extends BaseModel {
  static $columns = ['id', 'employeeId', 'orgId', 'email', 'otpHash', 'purpose', 'channel', 'attempts', 'maxAttempts', 'isUsed', 'expiresAt', 'usedAt', 'ipAddress', 'createdAt'] as const
  $columns = OtpTokenSchema.$columns
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare employeeId: number | null
  @column()
  declare orgId: number | null
  @column()
  declare email: string
  @column()
  declare otpHash: string
  @column()
  declare purpose: string
  @column()
  declare channel: string
  @column()
  declare attempts: boolean
  @column()
  declare maxAttempts: boolean
  @column()
  declare isUsed: boolean
  @column.dateTime()
  declare expiresAt: DateTime
  @column.dateTime()
  declare usedAt: DateTime | null
  @column()
  declare ipAddress: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
}

export class PasswordHistorySchema extends BaseModel {
  static $columns = ['id', 'employeeId', 'passwordHash', 'createdAt'] as const
  $columns = PasswordHistorySchema.$columns
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare employeeId: number
  @column()
  declare passwordHash: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
}

export class PasswordResetTokenSchema extends BaseModel {
  static $columns = ['id', 'employeeId', 'token', 'expiresAt', 'createdAt'] as const
  $columns = PasswordResetTokenSchema.$columns
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare employeeId: number
  @column()
  declare token: string
  @column.dateTime()
  declare expiresAt: DateTime
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
}

export class PaymentSchema extends BaseModel {
  static $columns = ['id', 'orgId', 'planId', 'amount', 'currency', 'paymentMethod', 'transactionId', 'status', 'paidAt', 'createdAt'] as const
  $columns = PaymentSchema.$columns
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare orgId: number
  @column()
  declare planId: number | null
  @column()
  declare amount: string
  @column()
  declare currency: string | null
  @column()
  declare paymentMethod: string | null
  @column()
  declare transactionId: string | null
  @column()
  declare status: string | null
  @column.dateTime()
  declare paidAt: DateTime | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
}

export class PayrollSchema extends BaseModel {
  static $columns = ['id', 'employeeId', 'orgId', 'month', 'year', 'basicSalary', 'hra', 'allowances', 'bonus', 'grossSalary', 'pfDeduction', 'esiDeduction', 'tdsDeduction', 'otherDeductions', 'totalDeductions', 'netSalary', 'paymentDate', 'paymentMode', 'paymentRef', 'status', 'processedBy', 'isLocked', 'createdAt'] as const
  $columns = PayrollSchema.$columns
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare employeeId: number
  @column()
  declare orgId: number
  @column()
  declare month: boolean
  @column()
  declare year: number
  @column()
  declare basicSalary: string
  @column()
  declare hra: string | null
  @column()
  declare allowances: string | null
  @column()
  declare bonus: string | null
  @column()
  declare grossSalary: string | null
  @column()
  declare pfDeduction: string | null
  @column()
  declare esiDeduction: string | null
  @column()
  declare tdsDeduction: string | null
  @column()
  declare otherDeductions: string | null
  @column()
  declare totalDeductions: string | null
  @column()
  declare netSalary: string | null
  @column.date()
  declare paymentDate: DateTime | null
  @column()
  declare paymentMode: string | null
  @column()
  declare paymentRef: string | null
  @column()
  declare status: string | null
  @column()
  declare processedBy: number | null
  @column()
  declare isLocked: boolean
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
}

export class PayrollSettingSchema extends BaseModel {
  static $columns = ['id', 'orgId', 'pfPercent', 'esiPercent', 'taxSlabs', 'payDay', 'currency', 'createdAt'] as const
  $columns = PayrollSettingSchema.$columns
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare orgId: number
  @column()
  declare pfPercent: string | null
  @column()
  declare esiPercent: string | null
  @column()
  declare taxSlabs: string | null
  @column()
  declare payDay: boolean | null
  @column()
  declare currency: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
}

export class PermissionSchema extends BaseModel {
  static $columns = ['id', 'permissionKey', 'description', 'module'] as const
  $columns = PermissionSchema.$columns
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare permissionKey: string
  @column()
  declare description: string | null
  @column()
  declare module: string | null
}

export class PlanSchema extends BaseModel {
  static $columns = ['id', 'name', 'price', 'userLimit', 'durationDays', 'features', 'isActive', 'createdAt', 'updatedAt'] as const
  $columns = PlanSchema.$columns
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare name: string
  @column()
  declare price: string
  @column()
  declare userLimit: number
  @column()
  declare durationDays: number
  @column()
  declare features: string | null
  @column()
  declare isActive: boolean
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class ProjectSchema extends BaseModel {
  static $columns = ['id', 'orgId', 'name', 'description', 'clientName', 'startDate', 'endDate', 'budget', 'status', 'priority', 'createdBy', 'deletedAt', 'createdAt', 'updatedAt'] as const
  $columns = ProjectSchema.$columns
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare orgId: number
  @column()
  declare name: string
  @column()
  declare description: string | null
  @column()
  declare clientName: string | null
  @column.date()
  declare startDate: DateTime | null
  @column.date()
  declare endDate: DateTime | null
  @column()
  declare budget: string | null
  @column()
  declare status: string | null
  @column()
  declare priority: string | null
  @column()
  declare createdBy: number | null
  @column.dateTime()
  declare deletedAt: DateTime | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class ProjectMemberSchema extends BaseModel {
  static $columns = ['projectId', 'employeeId', 'role', 'joinedAt'] as const
  $columns = ProjectMemberSchema.$columns
  @column()
  declare projectId: number
  @column()
  declare employeeId: number
  @column()
  declare role: string | null
  @column.dateTime()
  declare joinedAt: DateTime
}

export class RefreshTokenSchema extends BaseModel {
  static $columns = ['id', 'employeeId', 'orgId', 'tokenHash', 'parentTokenHash', 'deviceId', 'isRememberMe', 'isRevoked', 'revokedAt', 'revokedReason', 'expiresAt', 'ipAddress', 'userAgent', 'lastUsedAt', 'createdAt'] as const
  $columns = RefreshTokenSchema.$columns
  @column({ isPrimary: true })
  declare id: bigint | number
  @column()
  declare employeeId: number
  @column()
  declare orgId: number
  @column()
  declare tokenHash: string
  @column()
  declare parentTokenHash: string | null
  @column()
  declare deviceId: string | null
  @column()
  declare isRememberMe: boolean
  @column()
  declare isRevoked: boolean
  @column.dateTime()
  declare revokedAt: DateTime | null
  @column()
  declare revokedReason: string | null
  @column.dateTime()
  declare expiresAt: DateTime
  @column()
  declare ipAddress: string | null
  @column()
  declare userAgent: string | null
  @column.dateTime()
  declare lastUsedAt: DateTime
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
}

export class RoleSchema extends BaseModel {
  static $columns = ['id', 'orgId', 'roleName', 'isSystem', 'createdAt', 'updatedAt'] as const
  $columns = RoleSchema.$columns
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare orgId: number | null
  @column()
  declare roleName: string
  @column()
  declare isSystem: boolean
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class RolePermissionSchema extends BaseModel {
  static $columns = ['roleId', 'permissionId', 'grantedAt'] as const
  $columns = RolePermissionSchema.$columns
  @column()
  declare roleId: number
  @column()
  declare permissionId: number
  @column.dateTime()
  declare grantedAt: DateTime
}

export class ShiftSchema extends BaseModel {
  static $columns = ['id', 'orgId', 'name', 'startTime', 'endTime', 'graceTime', 'workDays', 'createdAt'] as const
  $columns = ShiftSchema.$columns
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare orgId: number
  @column()
  declare name: string
  @column()
  declare startTime: string
  @column()
  declare endTime: string
  @column()
  declare graceTime: number | null
  @column()
  declare workDays: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
}

export class SocialLoginSchema extends BaseModel {
  static $columns = ['id', 'employeeId', 'provider', 'providerUserId', 'profileData', 'createdAt'] as const
  $columns = SocialLoginSchema.$columns
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare employeeId: number
  @column()
  declare provider: string
  @column()
  declare providerUserId: string
  @column()
  declare profileData: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
}

export class TaskSchema extends BaseModel {
  static $columns = ['id', 'orgId', 'projectId', 'assignedTo', 'title', 'description', 'priority', 'status', 'dueDate', 'estimatedHours', 'actualHours', 'createdAt', 'updatedAt'] as const
  $columns = TaskSchema.$columns
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare orgId: number
  @column()
  declare projectId: number
  @column()
  declare assignedTo: number | null
  @column()
  declare title: string
  @column()
  declare description: string | null
  @column()
  declare priority: string | null
  @column()
  declare status: string | null
  @column.date()
  declare dueDate: DateTime | null
  @column()
  declare estimatedHours: string | null
  @column()
  declare actualHours: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class TimesheetSchema extends BaseModel {
  static $columns = ['id', 'orgId', 'employeeId', 'projectId', 'taskId', 'workDate', 'durationMinutes', 'description', 'status', 'approvedBy', 'approvedAt', 'createdAt', 'updatedAt'] as const
  $columns = TimesheetSchema.$columns
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare orgId: number
  @column()
  declare employeeId: number
  @column()
  declare projectId: number
  @column()
  declare taskId: number | null
  @column.date()
  declare workDate: DateTime
  @column()
  declare durationMinutes: number
  @column()
  declare description: string | null
  @column()
  declare status: string | null
  @column()
  declare approvedBy: number | null
  @column.dateTime()
  declare approvedAt: DateTime | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class TrustedDeviceSchema extends BaseModel {
  static $columns = ['id', 'employeeId', 'deviceId', 'deviceName', 'trustedAt', 'lastUsedAt'] as const
  $columns = TrustedDeviceSchema.$columns
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare employeeId: number
  @column()
  declare deviceId: string
  @column()
  declare deviceName: string | null
  @column.dateTime()
  declare trustedAt: DateTime
  @column.dateTime()
  declare lastUsedAt: DateTime | null
}

export class UserSchema extends BaseModel {
  static $columns = ['id', 'fullName', 'email', 'password', 'createdAt', 'updatedAt'] as const
  $columns = UserSchema.$columns
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare fullName: string | null
  @column()
  declare email: string
  @column({ serializeAs: null })
  declare password: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class UserSessionSchema extends BaseModel {
  static $columns = ['id', 'employeeId', 'orgId', 'sessionToken', 'refreshToken', 'deviceInfo', 'ipAddress', 'userAgent', 'lastActivity', 'expiresAt', 'isRevoked', 'revokedAt', 'revokedReason', 'createdAt'] as const
  $columns = UserSessionSchema.$columns
  @column({ isPrimary: true })
  declare id: bigint | number
  @column()
  declare employeeId: number
  @column()
  declare orgId: number
  @column()
  declare sessionToken: string
  @column()
  declare refreshToken: string | null
  @column()
  declare deviceInfo: string | null
  @column()
  declare ipAddress: string | null
  @column()
  declare userAgent: string | null
  @column.dateTime()
  declare lastActivity: DateTime
  @column.dateTime()
  declare expiresAt: DateTime
  @column()
  declare isRevoked: boolean
  @column.dateTime()
  declare revokedAt: DateTime | null
  @column()
  declare revokedReason: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
}
