/**
 * This file is automatically generated
 * DO NOT EDIT manually
 * Run "node ace migration:run" command to re-generate this file
 */

import { BaseModel, column } from '@adonisjs/lucid/orm'
import { DateTime } from 'luxon'

export class AddonPriceSchema extends BaseModel {
  static $columns = ['id', 'name', 'slug', 'price', 'planType', 'isActive', 'createdAt', 'updatedAt'] as const
  $columns = AddonPriceSchema.$columns
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare name: string
  @column()
  declare slug: string
  @column()
  declare price: string
  @column()
  declare planType: boolean | null
  @column()
  declare isActive: boolean
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class AnnouncementSchema extends BaseModel {
  static $columns = ['id', 'orgId', 'title', 'content', 'target', 'targetId', 'publishedAt', 'expiresAt', 'createdBy', 'deletedAt', 'createdAt', 'priority', 'updatedAt'] as const
  $columns = AnnouncementSchema.$columns
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare orgId: number
  @column()
  declare title: string
  @column()
  declare content: string | null
  @column()
  declare target: string
  @column()
  declare targetId: number | null
  @column.dateTime()
  declare publishedAt: DateTime | null
  @column.dateTime()
  declare expiresAt: DateTime | null
  @column()
  declare createdBy: number | null
  @column.dateTime()
  declare deletedAt: DateTime | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare priority: string | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class ApiRateLimitSchema extends BaseModel {
  static $columns = ['id', 'identifier', 'endpoint', 'requestCount', 'windowStart', 'windowEnd', 'isBlocked', 'createdAt', 'updatedAt'] as const
  $columns = ApiRateLimitSchema.$columns
  @column({ isPrimary: true })
  declare id: bigint | number
  @column()
  declare identifier: string
  @column()
  declare endpoint: string
  @column()
  declare requestCount: number
  @column.dateTime()
  declare windowStart: DateTime
  @column.dateTime()
  declare windowEnd: DateTime
  @column()
  declare isBlocked: boolean
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class AttendanceSchema extends BaseModel {
  static $columns = ['id', 'employeeId', 'orgId', 'shiftId', 'attendanceDate', 'checkIn', 'checkOut', 'checkInLat', 'checkInLng', 'checkOutLat', 'checkOutLng', 'deviceInfo', 'selfieUrl', 'biometricRef', 'status', 'source', 'notes', 'modifiedBy', 'modifiedAt', 'createdAt', 'workHours', 'isLate', 'isHalfDay', 'isOvertime', 'totalBreakMin', 'netWorkHours', 'breakStart', 'breakEnd', 'breakDuration'] as const
  $columns = AttendanceSchema.$columns
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare employeeId: number
  @column()
  declare orgId: number
  @column()
  declare shiftId: number | null
  @column.date()
  declare attendanceDate: DateTime
  @column.dateTime()
  declare checkIn: DateTime | null
  @column.dateTime()
  declare checkOut: DateTime | null
  @column()
  declare checkInLat: string | null
  @column()
  declare checkInLng: string | null
  @column()
  declare checkOutLat: string | null
  @column()
  declare checkOutLng: string | null
  @column()
  declare deviceInfo: string | null
  @column()
  declare selfieUrl: string | null
  @column()
  declare biometricRef: string | null
  @column()
  declare status: string
  @column()
  declare source: string
  @column()
  declare notes: string | null
  @column()
  declare modifiedBy: number | null
  @column.dateTime()
  declare modifiedAt: DateTime | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare workHours: string | null
  @column()
  declare isLate: boolean
  @column()
  declare isHalfDay: boolean
  @column()
  declare isOvertime: boolean
  @column()
  declare totalBreakMin: number
  @column()
  declare netWorkHours: string
  @column.dateTime()
  declare breakStart: DateTime | null
  @column.dateTime()
  declare breakEnd: DateTime | null
  @column()
  declare breakDuration: number | null
}

export class AttendanceLogSchema extends BaseModel {
  static $columns = ['id', 'orgId', 'employeeId', 'kioskId', 'attendanceDate', 'type', 'method', 'timestamp', 'shiftId', 'status', 'lateMinutes', 'earlyExitMinutes', 'overtimeMinutes', 'ipAddress', 'deviceId', 'clientReference', 'imageUrl', 'failureReason', 'createdAt', 'updatedAt'] as const
  $columns = AttendanceLogSchema.$columns
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare orgId: number
  @column()
  declare employeeId: number | null
  @column()
  declare kioskId: number | null
  @column.date()
  declare attendanceDate: DateTime
  @column()
  declare type: string
  @column()
  declare method: string
  @column.dateTime()
  declare timestamp: DateTime
  @column()
  declare shiftId: number | null
  @column()
  declare status: string
  @column()
  declare lateMinutes: number
  @column()
  declare earlyExitMinutes: number
  @column()
  declare overtimeMinutes: number
  @column()
  declare ipAddress: string | null
  @column()
  declare deviceId: string | null
  @column()
  declare clientReference: string | null
  @column()
  declare imageUrl: string | null
  @column()
  declare failureReason: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class AttendanceRegularizationSchema extends BaseModel {
  static $columns = ['id', 'employeeId', 'orgId', 'attendanceId', 'regularizationDate', 'checkIn', 'checkOut', 'type', 'reason', 'status', 'adminNotes', 'rejectionReason', 'approvedBy', 'approvedAt', 'createdAt', 'updatedAt'] as const
  $columns = AttendanceRegularizationSchema.$columns
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare employeeId: number
  @column()
  declare orgId: number
  @column()
  declare attendanceId: number | null
  @column.date()
  declare regularizationDate: DateTime
  @column()
  declare checkIn: string | null
  @column()
  declare checkOut: string | null
  @column()
  declare type: string
  @column()
  declare reason: string
  @column()
  declare status: string | null
  @column()
  declare adminNotes: string | null
  @column()
  declare rejectionReason: string | null
  @column()
  declare approvedBy: number | null
  @column.dateTime()
  declare approvedAt: DateTime | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class AuditLogSchema extends BaseModel {
  static $columns = ['id', 'orgId', 'employeeId', 'action', 'module', 'entityName', 'entityId', 'oldValues', 'newValues', 'ipAddress', 'countryCode', 'countryName', 'userAgent', 'isImmutable', 'createdAt', 'cityName', 'regionName', 'latitude', 'longitude'] as const
  $columns = AuditLogSchema.$columns
  @column({ isPrimary: true })
  declare id: bigint | number
  @column()
  declare orgId: number | null
  @column()
  declare employeeId: number | null
  @column()
  declare action: string
  @column()
  declare module: string
  @column()
  declare entityName: string | null
  @column()
  declare entityId: string | null
  @column()
  declare oldValues: string | null
  @column()
  declare newValues: string | null
  @column()
  declare ipAddress: string | null
  @column()
  declare countryCode: string | null
  @column()
  declare countryName: string | null
  @column()
  declare userAgent: string | null
  @column()
  declare isImmutable: boolean
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare cityName: string | null
  @column()
  declare regionName: string | null
  @column()
  declare latitude: string | null
  @column()
  declare longitude: string | null
}

export class AuthAccessTokenSchema extends BaseModel {
  static $columns = ['id', 'tokenableId', 'type', 'name', 'hash', 'abilities', 'createdAt', 'updatedAt', 'lastUsedAt', 'expiresAt'] as const
  $columns = AuthAccessTokenSchema.$columns
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare tokenableId: number
  @column()
  declare type: string
  @column()
  declare name: string | null
  @column()
  declare hash: string
  @column()
  declare abilities: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
  @column.dateTime()
  declare lastUsedAt: DateTime | null
  @column.dateTime()
  declare expiresAt: DateTime | null
}

export class CountrySchema extends BaseModel {
  static $columns = ['id', 'name', 'code', 'flag', 'phoneNumberLength', 'isActive', 'createdAt', 'updatedAt'] as const
  $columns = CountrySchema.$columns
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare name: string
  @column()
  declare code: string
  @column()
  declare flag: string
  @column()
  declare phoneNumberLength: number | null
  @column()
  declare isActive: boolean
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class DataErasureRequestSchema extends BaseModel {
  static $columns = ['id', 'employeeId', 'orgId', 'email', 'reason', 'status', 'requestedAt', 'completedAt', 'processedBy', 'adminNote'] as const
  $columns = DataErasureRequestSchema.$columns
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare employeeId: number
  @column()
  declare orgId: number
  @column()
  declare email: string
  @column()
  declare reason: string | null
  @column()
  declare status: string
  @column.dateTime()
  declare requestedAt: DateTime
  @column.dateTime()
  declare completedAt: DateTime | null
  @column()
  declare processedBy: number | null
  @column()
  declare adminNote: string | null
}

export class DepartmentSchema extends BaseModel {
  static $columns = ['id', 'orgId', 'parentId', 'departmentName', 'description', 'isActive', 'deletedAt'] as const
  $columns = DepartmentSchema.$columns
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare orgId: number
  @column()
  declare parentId: number | null
  @column()
  declare departmentName: string
  @column()
  declare description: string | null
  @column()
  declare isActive: boolean
  @column.dateTime()
  declare deletedAt: DateTime | null
}

export class DesignationSchema extends BaseModel {
  static $columns = ['id', 'orgId', 'departmentId', 'designationName'] as const
  $columns = DesignationSchema.$columns
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare orgId: number
  @column()
  declare departmentId: number | null
  @column()
  declare designationName: string
}

export class DocumentSchema extends BaseModel {
  static $columns = ['id', 'orgId', 'employeeId', 'title', 'fileName', 'filePath', 'fileUuid', 'fileType', 'fileSizeKb', 'mimeType', 'category', 'description', 'isPrivate', 'isEncrypted', 'checksum', 'uploadedBy', 'deletedAt', 'createdAt'] as const
  $columns = DocumentSchema.$columns
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare orgId: number
  @column()
  declare employeeId: number | null
  @column()
  declare title: string
  @column()
  declare fileName: string | null
  @column()
  declare filePath: string | null
  @column()
  declare fileUuid: string
  @column()
  declare fileType: string | null
  @column()
  declare fileSizeKb: number | null
  @column()
  declare mimeType: string | null
  @column()
  declare category: string | null
  @column()
  declare description: string | null
  @column()
  declare isPrivate: boolean
  @column()
  declare isEncrypted: boolean
  @column()
  declare checksum: string | null
  @column()
  declare uploadedBy: number | null
  @column.dateTime()
  declare deletedAt: DateTime | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
}

export class DocumentAccessLogSchema extends BaseModel {
  static $columns = ['id', 'documentId', 'employeeId', 'orgId', 'action', 'ipAddress', 'userAgent', 'accessedAt'] as const
  $columns = DocumentAccessLogSchema.$columns
  @column({ isPrimary: true })
  declare id: bigint | number
  @column()
  declare documentId: number
  @column()
  declare employeeId: number
  @column()
  declare orgId: number
  @column()
  declare action: string
  @column()
  declare ipAddress: string | null
  @column()
  declare userAgent: string | null
  @column.dateTime()
  declare accessedAt: DateTime
}

export class EmailVerificationTokenSchema extends BaseModel {
  static $columns = ['id', 'employeeId', 'token', 'expiresAt', 'createdAt'] as const
  $columns = EmailVerificationTokenSchema.$columns
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare employeeId: number
  @column()
  declare token: string
  @column.dateTime()
  declare expiresAt: DateTime
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
}

export class EmployeeSchema extends BaseModel {
  static $columns = ['id', 'orgId', 'departmentId', 'designationId', 'geofenceId', 'roleId', 'managerId', 'employeeCode', 'firstName', 'lastName', 'email', 'phone', 'passwordHash', 'kioskPinHash', 'kioskPinAttempts', 'kioskPinBlockedUntil', 'mustChangePassword', 'isLocked', 'lockedUntil', 'avatar', 'gender', 'dateOfBirth', 'address', 'emergencyContact', 'emergencyPhone', 'salary', 'bankAccount', 'bankName', 'ifscCode', 'panNumber', 'aadharLast4', 'joinDate', 'exitDate', 'exitReason', 'status', 'emailVerified', 'deletedAt', 'deletedBy', 'createdAt', 'updatedAt', 'phoneVerified', 'phoneAuthEnabled', 'loginType', 'isInternational', 'countryCode', 'countryName'] as const
  $columns = EmployeeSchema.$columns
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare orgId: number
  @column()
  declare departmentId: number | null
  @column()
  declare designationId: number | null
  @column()
  declare geofenceId: number | null
  @column()
  declare roleId: number | null
  @column()
  declare managerId: number | null
  @column()
  declare employeeCode: string | null
  @column()
  declare firstName: string
  @column()
  declare lastName: string | null
  @column()
  declare email: string | null
  @column()
  declare phone: string | null
  @column()
  declare passwordHash: string | null
  @column()
  declare kioskPinHash: string | null
  @column()
  declare kioskPinAttempts: number
  @column.dateTime()
  declare kioskPinBlockedUntil: DateTime | null
  @column()
  declare mustChangePassword: boolean
  @column()
  declare isLocked: boolean
  @column.dateTime()
  declare lockedUntil: DateTime | null
  @column()
  declare avatar: string | null
  @column()
  declare gender: string | null
  @column.date()
  declare dateOfBirth: DateTime | null
  @column()
  declare address: string | null
  @column()
  declare emergencyContact: string | null
  @column()
  declare emergencyPhone: string | null
  @column()
  declare salary: string
  @column()
  declare bankAccount: string | null
  @column()
  declare bankName: string | null
  @column()
  declare ifscCode: string | null
  @column()
  declare panNumber: string | null
  @column()
  declare aadharLast4: string | null
  @column.date()
  declare joinDate: DateTime | null
  @column.date()
  declare exitDate: DateTime | null
  @column()
  declare exitReason: string | null
  @column()
  declare status: string
  @column()
  declare emailVerified: boolean
  @column.dateTime()
  declare deletedAt: DateTime | null
  @column()
  declare deletedBy: number | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
  @column()
  declare phoneVerified: boolean
  @column()
  declare phoneAuthEnabled: boolean
  @column()
  declare loginType: string | null
  @column()
  declare isInternational: boolean
  @column()
  declare countryCode: string | null
  @column()
  declare countryName: string | null
}

export class EmployeeEducationSchema extends BaseModel {
  static $columns = ['id', 'employeeId', 'institution', 'degree', 'fieldOfStudy', 'startDate', 'endDate', 'grade', 'description', 'createdAt', 'updatedAt'] as const
  $columns = EmployeeEducationSchema.$columns
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare employeeId: number
  @column()
  declare institution: string
  @column()
  declare degree: string
  @column()
  declare fieldOfStudy: string | null
  @column.date()
  declare startDate: DateTime | null
  @column.date()
  declare endDate: DateTime | null
  @column()
  declare grade: string | null
  @column()
  declare description: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class EmployeeExperienceSchema extends BaseModel {
  static $columns = ['id', 'employeeId', 'companyName', 'role', 'location', 'startDate', 'endDate', 'isCurrent', 'description', 'createdAt', 'updatedAt'] as const
  $columns = EmployeeExperienceSchema.$columns
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare employeeId: number
  @column()
  declare companyName: string
  @column()
  declare role: string
  @column()
  declare location: string | null
  @column.date()
  declare startDate: DateTime
  @column.date()
  declare endDate: DateTime | null
  @column()
  declare isCurrent: boolean
  @column()
  declare description: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class EmployeeFaceProfileSchema extends BaseModel {
  static $columns = ['id', 'orgId', 'employeeId', 'faceEmbedding', 'referenceImageUrl', 'status', 'createdBy', 'approvedBy', 'approvedAt', 'createdAt', 'updatedAt'] as const
  $columns = EmployeeFaceProfileSchema.$columns
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare orgId: number
  @column()
  declare employeeId: number
  @column()
  declare faceEmbedding: string
  @column()
  declare referenceImageUrl: string | null
  @column()
  declare status: string
  @column()
  declare createdBy: number | null
  @column()
  declare approvedBy: number | null
  @column.dateTime()
  declare approvedAt: DateTime | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class EmployeeInvitationSchema extends BaseModel {
  static $columns = ['id', 'orgId', 'email', 'roleId', 'token', 'status', 'expiresAt', 'invitedBy', 'createdAt', 'updatedAt'] as const
  $columns = EmployeeInvitationSchema.$columns
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare orgId: number
  @column()
  declare email: string
  @column()
  declare roleId: number | null
  @column()
  declare token: string
  @column()
  declare status: string
  @column.dateTime()
  declare expiresAt: DateTime
  @column()
  declare invitedBy: number | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class EmployeeShiftSchema extends BaseModel {
  static $columns = ['id', 'employeeId', 'shiftId', 'effectiveFrom', 'effectiveTo'] as const
  $columns = EmployeeShiftSchema.$columns
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare employeeId: number
  @column()
  declare shiftId: number
  @column.date()
  declare effectiveFrom: DateTime
  @column.date()
  declare effectiveTo: DateTime | null
}

export class EssRequestSchema extends BaseModel {
  static $columns = ['id', 'orgId', 'employeeId', 'approverEmployeeId', 'requestType', 'title', 'description', 'requestDate', 'startDate', 'endDate', 'amount', 'status', 'attachmentUrl', 'meta', 'resolutionNote', 'resolvedAt', 'createdAt', 'updatedAt'] as const
  $columns = EssRequestSchema.$columns
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare orgId: number
  @column()
  declare employeeId: number
  @column()
  declare approverEmployeeId: number | null
  @column()
  declare requestType: string
  @column()
  declare title: string
  @column()
  declare description: string | null
  @column.date()
  declare requestDate: DateTime | null
  @column.date()
  declare startDate: DateTime | null
  @column.date()
  declare endDate: DateTime | null
  @column()
  declare amount: string | null
  @column()
  declare status: string
  @column()
  declare attachmentUrl: string | null
  @column()
  declare meta: string | null
  @column()
  declare resolutionNote: string | null
  @column.dateTime()
  declare resolvedAt: DateTime | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class ExpenseSchema extends BaseModel {
  static $columns = ['id', 'orgId', 'employeeId', 'projectId', 'category', 'amount', 'expenseDate', 'description', 'receiptUrl', 'status', 'approvedBy', 'approvedAt', 'rejectionNote', 'deletedAt', 'createdAt', 'updatedAt'] as const
  $columns = ExpenseSchema.$columns
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare orgId: number
  @column()
  declare employeeId: number
  @column()
  declare projectId: number | null
  @column()
  declare category: string | null
  @column()
  declare amount: string
  @column.date()
  declare expenseDate: DateTime
  @column()
  declare description: string | null
  @column()
  declare receiptUrl: string | null
  @column()
  declare status: string
  @column()
  declare approvedBy: number | null
  @column.dateTime()
  declare approvedAt: DateTime | null
  @column()
  declare rejectionNote: string | null
  @column.dateTime()
  declare deletedAt: DateTime | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class FaceEmbeddingSchema extends BaseModel {
  static $columns = ['id', 'employeeId', 'orgId', 'embedding', 'imageUrl', 'isActive', 'createdAt', 'updatedAt'] as const
  $columns = FaceEmbeddingSchema.$columns
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare employeeId: number
  @column()
  declare orgId: number
  @column()
  declare embedding: string
  @column()
  declare imageUrl: string | null
  @column()
  declare isActive: boolean
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class FeatureLimitSchema extends BaseModel {
  static $columns = ['id', 'planId', 'featureKey', 'featureLabel', 'featureType', 'isEnabled', 'limitValue', 'metadata', 'createdAt', 'updatedAt'] as const
  $columns = FeatureLimitSchema.$columns
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare planId: number
  @column()
  declare featureKey: string
  @column()
  declare featureLabel: string | null
  @column()
  declare featureType: string
  @column()
  declare isEnabled: boolean
  @column()
  declare limitValue: string | null
  @column()
  declare metadata: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class HolidaySchema extends BaseModel {
  static $columns = ['id', 'orgId', 'name', 'holidayDate', 'type', 'isActive', 'createdAt'] as const
  $columns = HolidaySchema.$columns
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare orgId: number
  @column()
  declare name: string
  @column.date()
  declare holidayDate: DateTime
  @column()
  declare type: string
  @column()
  declare isActive: boolean
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
}

export class InvoiceSchema extends BaseModel {
  static $columns = ['id', 'paymentId', 'orgId', 'invoiceNumber', 'subtotal', 'taxPercent', 'notes', 'isVoid', 'voidReason', 'createdAt', 'taxAmount', 'total'] as const
  $columns = InvoiceSchema.$columns
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare paymentId: number
  @column()
  declare orgId: number
  @column()
  declare invoiceNumber: string
  @column()
  declare subtotal: string
  @column()
  declare taxPercent: string
  @column()
  declare notes: string | null
  @column()
  declare isVoid: boolean
  @column()
  declare voidReason: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare taxAmount: string | null
  @column()
  declare total: string | null
}

export class KioskSchema extends BaseModel {
  static $columns = ['id', 'orgId', 'orgLocationId', 'name', 'location', 'deviceId', 'deviceToken', 'status', 'lastSeenAt', 'registeredBy', 'approvedBy', 'approvedAt', 'createdAt', 'updatedAt'] as const
  $columns = KioskSchema.$columns
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare orgId: number
  @column()
  declare orgLocationId: number | null
  @column()
  declare name: string
  @column()
  declare location: string
  @column()
  declare deviceId: string
  @column()
  declare deviceToken: string | null
  @column()
  declare status: string
  @column.dateTime()
  declare lastSeenAt: DateTime | null
  @column()
  declare registeredBy: number | null
  @column()
  declare approvedBy: number | null
  @column.dateTime()
  declare approvedAt: DateTime | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class LeafSchema extends BaseModel {
  static $columns = ['id', 'employeeId', 'orgId', 'leaveTypeId', 'startDate', 'endDate', 'reason', 'supportingDoc', 'status', 'approvedBy', 'approvedAt', 'rejectionNote', 'deletedAt', 'cancelledBy', 'cancelledAt', 'createdAt', 'updatedAt', 'totalDays'] as const
  $columns = LeafSchema.$columns
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare employeeId: number
  @column()
  declare orgId: number
  @column()
  declare leaveTypeId: number | null
  @column.date()
  declare startDate: DateTime
  @column.date()
  declare endDate: DateTime
  @column()
  declare reason: string | null
  @column()
  declare supportingDoc: string | null
  @column()
  declare status: string
  @column()
  declare approvedBy: number | null
  @column.dateTime()
  declare approvedAt: DateTime | null
  @column()
  declare rejectionNote: string | null
  @column.dateTime()
  declare deletedAt: DateTime | null
  @column()
  declare cancelledBy: number | null
  @column.dateTime()
  declare cancelledAt: DateTime | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare totalDays: string | null
}

export class LeaveTypeSchema extends BaseModel {
  static $columns = ['id', 'orgId', 'typeName', 'daysAllowed', 'carryForward', 'maxCarryDays', 'isPaid', 'requiresDoc'] as const
  $columns = LeaveTypeSchema.$columns
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare orgId: number
  @column()
  declare typeName: string
  @column()
  declare daysAllowed: number
  @column()
  declare carryForward: boolean
  @column()
  declare maxCarryDays: number
  @column()
  declare isPaid: boolean
  @column()
  declare requiresDoc: boolean
}

export class LoginAttemptSchema extends BaseModel {
  static $columns = ['id', 'employeeId', 'orgId', 'email', 'ipAddress', 'userAgent', 'attemptType', 'status', 'failureReason', 'createdAt'] as const
  $columns = LoginAttemptSchema.$columns
  @column({ isPrimary: true })
  declare id: bigint | number
  @column()
  declare employeeId: number | null
  @column()
  declare orgId: number | null
  @column()
  declare email: string
  @column()
  declare ipAddress: string
  @column()
  declare userAgent: string | null
  @column()
  declare attemptType: string
  @column()
  declare status: string
  @column()
  declare failureReason: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
}

export class MagicLinkTokenSchema extends BaseModel {
  static $columns = ['id', 'employeeId', 'token', 'expiresAt', 'isUsed', 'createdAt'] as const
  $columns = MagicLinkTokenSchema.$columns
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare employeeId: number
  @column()
  declare token: string
  @column.dateTime()
  declare expiresAt: DateTime
  @column()
  declare isUsed: boolean
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
}

export class NotificationSchema extends BaseModel {
  static $columns = ['id', 'employeeId', 'orgId', 'title', 'message', 'type', 'link', 'isRead', 'readAt', 'createdAt'] as const
  $columns = NotificationSchema.$columns
  @column({ isPrimary: true })
  declare id: bigint | number
  @column()
  declare employeeId: number
  @column()
  declare orgId: number
  @column()
  declare title: string
  @column()
  declare message: string
  @column()
  declare type: string | null
  @column()
  declare link: string | null
  @column()
  declare isRead: boolean
  @column.dateTime()
  declare readAt: DateTime | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
}

export class OrganizationSchema extends BaseModel {
  static $columns = ['id', 'companyName', 'slug', 'email', 'phone', 'address', 'city', 'state', 'country', 'postalCode', 'gstin', 'logo', 'planId', 'planStatus', 'planEndDate', 'userLimit', 'isActive', 'isVerified', 'verificationToken', 'timezone', 'deletedAt', 'deletedBy', 'createdAt', 'updatedAt', 'geofenceEnabled', 'requireGeofenceForAll', 'defaultGeofenceId', 'orgType', 'defaultLanguage', 'allowedLoginMethods', 'trialStartDate', 'trialEndDate', 'isTrialActive', 'subscriptionStatus', 'gracePeriodEndDate', 'readOnlyMode', 'subscriptionLastNotifiedAt'] as const
  $columns = OrganizationSchema.$columns
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare companyName: string
  @column()
  declare slug: string
  @column()
  declare email: string
  @column()
  declare phone: string | null
  @column()
  declare address: string | null
  @column()
  declare city: string | null
  @column()
  declare state: string | null
  @column()
  declare country: string | null
  @column()
  declare postalCode: string | null
  @column()
  declare gstin: string | null
  @column()
  declare logo: string | null
  @column()
  declare planId: number | null
  @column()
  declare planStatus: boolean
  @column.date()
  declare planEndDate: DateTime | null
  @column()
  declare userLimit: number
  @column()
  declare isActive: boolean
  @column()
  declare isVerified: boolean
  @column()
  declare verificationToken: string | null
  @column()
  declare timezone: string
  @column.dateTime()
  declare deletedAt: DateTime | null
  @column()
  declare deletedBy: number | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
  @column()
  declare geofenceEnabled: boolean | null
  @column()
  declare requireGeofenceForAll: boolean | null
  @column()
  declare defaultGeofenceId: number | null
  @column()
  declare orgType: string | null
  @column()
  declare defaultLanguage: string | null
  @column()
  declare allowedLoginMethods: string | null
  @column.date()
  declare trialStartDate: DateTime | null
  @column.date()
  declare trialEndDate: DateTime | null
  @column()
  declare isTrialActive: boolean
  @column()
  declare subscriptionStatus: string
  @column.date()
  declare gracePeriodEndDate: DateTime | null
  @column()
  declare readOnlyMode: boolean
  @column.dateTime()
  declare subscriptionLastNotifiedAt: DateTime | null
}

export class OrganizationAddonSchema extends BaseModel {
  static $columns = ['id', 'orgId', 'addonId', 'startDate', 'endDate', 'isActive', 'createdAt', 'updatedAt'] as const
  $columns = OrganizationAddonSchema.$columns
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare orgId: number
  @column()
  declare addonId: number
  @column.date()
  declare startDate: DateTime
  @column.date()
  declare endDate: DateTime | null
  @column()
  declare isActive: boolean
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class OrganizationSettingSchema extends BaseModel {
  static $columns = ['id', 'orgId', 'settingKey', 'settingValue', 'createdAt', 'updatedAt'] as const
  $columns = OrganizationSettingSchema.$columns
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare orgId: number
  @column()
  declare settingKey: string
  @column()
  declare settingValue: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class OrgIpWhitelistSchema extends BaseModel {
  static $columns = ['id', 'orgId', 'ipCidr', 'label', 'isActive', 'createdBy', 'createdAt'] as const
  $columns = OrgIpWhitelistSchema.$columns
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare orgId: number
  @column()
  declare ipCidr: string
  @column()
  declare label: string | null
  @column()
  declare isActive: boolean
  @column()
  declare createdBy: number | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
}

export class OrgLocationSchema extends BaseModel {
  static $columns = ['id', 'orgId', 'name', 'latitude', 'longitude', 'radiusMeters', 'address', 'isActive', 'createdAt', 'updatedAt'] as const
  $columns = OrgLocationSchema.$columns
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare orgId: number
  @column()
  declare name: string
  @column()
  declare latitude: string
  @column()
  declare longitude: string
  @column()
  declare radiusMeters: number
  @column()
  declare address: string | null
  @column()
  declare isActive: boolean
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class OrgRegistrationSchema extends BaseModel {
  static $columns = ['id', 'orgName', 'adminEmail', 'adminPhone', 'verificationToken', 'status', 'onboardingData', 'createdAt'] as const
  $columns = OrgRegistrationSchema.$columns
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare orgName: string
  @column()
  declare adminEmail: string
  @column()
  declare adminPhone: string | null
  @column()
  declare verificationToken: string
  @column()
  declare status: string
  @column()
  declare onboardingData: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
}

export class OtpTokenSchema extends BaseModel {
  static $columns = ['id', 'employeeId', 'orgId', 'email', 'otpHash', 'purpose', 'channel', 'attempts', 'maxAttempts', 'isUsed', 'expiresAt', 'usedAt', 'ipAddress', 'createdAt'] as const
  $columns = OtpTokenSchema.$columns
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare employeeId: number | null
  @column()
  declare orgId: number | null
  @column()
  declare email: string
  @column()
  declare otpHash: string
  @column()
  declare purpose: string
  @column()
  declare channel: string
  @column()
  declare attempts: boolean
  @column()
  declare maxAttempts: boolean
  @column()
  declare isUsed: boolean
  @column.dateTime()
  declare expiresAt: DateTime
  @column.dateTime()
  declare usedAt: DateTime | null
  @column()
  declare ipAddress: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
}

export class OvertimeRequestSchema extends BaseModel {
  static $columns = ['id', 'employeeId', 'orgId', 'date', 'hours', 'reason', 'status', 'approvedBy', 'approvedAt', 'rejectionReason', 'createdAt', 'updatedAt'] as const
  $columns = OvertimeRequestSchema.$columns
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare employeeId: number
  @column()
  declare orgId: number
  @column.date()
  declare date: DateTime
  @column()
  declare hours: string
  @column()
  declare reason: string
  @column()
  declare status: string | null
  @column()
  declare approvedBy: number | null
  @column.dateTime()
  declare approvedAt: DateTime | null
  @column()
  declare rejectionReason: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class PasswordHistorySchema extends BaseModel {
  static $columns = ['id', 'employeeId', 'passwordHash', 'createdAt'] as const
  $columns = PasswordHistorySchema.$columns
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare employeeId: number
  @column()
  declare passwordHash: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
}

export class PasswordResetTokenSchema extends BaseModel {
  static $columns = ['id', 'employeeId', 'token', 'expiresAt', 'createdAt'] as const
  $columns = PasswordResetTokenSchema.$columns
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare employeeId: number
  @column()
  declare token: string
  @column.dateTime()
  declare expiresAt: DateTime
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
}

export class PaymentSchema extends BaseModel {
  static $columns = ['id', 'orgId', 'planId', 'amount', 'currency', 'paymentMethod', 'paymentGateway', 'transactionId', 'gatewayResponse', 'idempotencyKey', 'status', 'paidAt', 'refundedAt', 'refundAmount', 'refundRef', 'createdAt', 'provider', 'providerOrderId', 'providerPaymentId', 'providerSignature', 'billingCycle', 'failureReason', 'invoiceUrl', 'webhookEventId', 'metadata'] as const
  $columns = PaymentSchema.$columns
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare orgId: number
  @column()
  declare planId: number | null
  @column()
  declare amount: string
  @column()
  declare currency: string
  @column()
  declare paymentMethod: string | null
  @column()
  declare paymentGateway: string | null
  @column()
  declare transactionId: string | null
  @column()
  declare gatewayResponse: string | null
  @column()
  declare idempotencyKey: string | null
  @column()
  declare status: string
  @column.dateTime()
  declare paidAt: DateTime | null
  @column.dateTime()
  declare refundedAt: DateTime | null
  @column()
  declare refundAmount: string | null
  @column()
  declare refundRef: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare provider: string | null
  @column()
  declare providerOrderId: string | null
  @column()
  declare providerPaymentId: string | null
  @column()
  declare providerSignature: string | null
  @column()
  declare billingCycle: string | null
  @column()
  declare failureReason: string | null
  @column()
  declare invoiceUrl: string | null
  @column()
  declare webhookEventId: string | null
  @column()
  declare metadata: string | null
}

export class PayrollSchema extends BaseModel {
  static $columns = ['id', 'employeeId', 'orgId', 'month', 'year', 'basicSalary', 'hra', 'allowances', 'bonus', 'pfDeduction', 'esiDeduction', 'tdsDeduction', 'otherDeductions', 'paymentDate', 'paymentMode', 'paymentRef', 'status', 'processedBy', 'isLocked', 'createdAt', 'grossSalary', 'totalDeductions', 'netSalary'] as const
  $columns = PayrollSchema.$columns
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare employeeId: number
  @column()
  declare orgId: number
  @column()
  declare month: boolean
  @column()
  declare year: number
  @column()
  declare basicSalary: string
  @column()
  declare hra: string
  @column()
  declare allowances: string
  @column()
  declare bonus: string
  @column()
  declare pfDeduction: string
  @column()
  declare esiDeduction: string
  @column()
  declare tdsDeduction: string
  @column()
  declare otherDeductions: string
  @column.date()
  declare paymentDate: DateTime | null
  @column()
  declare paymentMode: string | null
  @column()
  declare paymentRef: string | null
  @column()
  declare status: string
  @column()
  declare processedBy: number | null
  @column()
  declare isLocked: boolean
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare grossSalary: string | null
  @column()
  declare totalDeductions: string | null
  @column()
  declare netSalary: string | null
}

export class PayrollSettingSchema extends BaseModel {
  static $columns = ['id', 'orgId', 'pfPercent', 'esiPercent', 'tdsPercent', 'createdAt', 'updatedAt'] as const
  $columns = PayrollSettingSchema.$columns
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare orgId: number
  @column()
  declare pfPercent: string
  @column()
  declare esiPercent: string
  @column()
  declare tdsPercent: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class PermissionSchema extends BaseModel {
  static $columns = ['id', 'permissionKey', 'description', 'module', 'resource', 'action', 'isSystem', 'createdAt', 'updatedAt'] as const
  $columns = PermissionSchema.$columns
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare permissionKey: string
  @column()
  declare description: string | null
  @column()
  declare module: string | null
  @column()
  declare resource: string | null
  @column()
  declare action: string | null
  @column()
  declare isSystem: boolean
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class PlanSchema extends BaseModel {
  static $columns = ['id', 'name', 'price', 'userLimit', 'durationDays', 'features', 'isActive', 'createdAt', 'updatedAt', 'slug', 'monthlyPrice', 'yearlyPrice', 'currency', 'storageLimitMb', 'sortOrder', 'isPublic', 'isTrialPlan', 'modules'] as const
  $columns = PlanSchema.$columns
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare name: string
  @column()
  declare price: string
  @column()
  declare userLimit: number
  @column()
  declare durationDays: number
  @column()
  declare features: string | null
  @column()
  declare isActive: boolean
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
  @column()
  declare slug: string | null
  @column()
  declare monthlyPrice: string
  @column()
  declare yearlyPrice: string
  @column()
  declare currency: string
  @column()
  declare storageLimitMb: number
  @column()
  declare sortOrder: number
  @column()
  declare isPublic: boolean
  @column()
  declare isTrialPlan: boolean
  @column()
  declare modules: string | null
}

export class ProjectSchema extends BaseModel {
  static $columns = ['id', 'orgId', 'name', 'description', 'clientName', 'startDate', 'endDate', 'budget', 'status', 'priority', 'createdBy', 'deletedAt', 'createdAt', 'updatedAt'] as const
  $columns = ProjectSchema.$columns
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare orgId: number
  @column()
  declare name: string
  @column()
  declare description: string | null
  @column()
  declare clientName: string | null
  @column.date()
  declare startDate: DateTime | null
  @column.date()
  declare endDate: DateTime | null
  @column()
  declare budget: string | null
  @column()
  declare status: string
  @column()
  declare priority: string
  @column()
  declare createdBy: number | null
  @column.dateTime()
  declare deletedAt: DateTime | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class ProjectMemberSchema extends BaseModel {
  static $columns = ['projectId', 'employeeId', 'role', 'addedBy', 'addedAt'] as const
  $columns = ProjectMemberSchema.$columns
  @column()
  declare projectId: number
  @column()
  declare employeeId: number
  @column()
  declare role: string
  @column()
  declare addedBy: number | null
  @column.dateTime()
  declare addedAt: DateTime
}

export class RefreshTokenSchema extends BaseModel {
  static $columns = ['id', 'employeeId', 'token', 'expiresAt', 'isRevoked', 'createdAt'] as const
  $columns = RefreshTokenSchema.$columns
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare employeeId: number
  @column()
  declare token: string
  @column.dateTime()
  declare expiresAt: DateTime
  @column()
  declare isRevoked: boolean
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
}

export class RoleSchema extends BaseModel {
  static $columns = ['id', 'orgId', 'roleName', 'description', 'parentRoleId', 'isSystem', 'priority', 'isActive', 'createdAt', 'updatedAt'] as const
  $columns = RoleSchema.$columns
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare orgId: number | null
  @column()
  declare roleName: string
  @column()
  declare description: string | null
  @column()
  declare parentRoleId: number | null
  @column()
  declare isSystem: boolean
  @column()
  declare priority: number
  @column()
  declare isActive: boolean
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class RolePermissionSchema extends BaseModel {
  static $columns = ['roleId', 'permissionId', 'grantedBy', 'grantedAt'] as const
  $columns = RolePermissionSchema.$columns
  @column()
  declare roleId: number
  @column()
  declare permissionId: number
  @column()
  declare grantedBy: number | null
  @column.dateTime()
  declare grantedAt: DateTime
}

export class ShiftSchema extends BaseModel {
  static $columns = ['id', 'orgId', 'shiftName', 'startTime', 'endTime', 'graceMinutes', 'isActive'] as const
  $columns = ShiftSchema.$columns
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare orgId: number
  @column()
  declare shiftName: string
  @column()
  declare startTime: string
  @column()
  declare endTime: string
  @column()
  declare graceMinutes: number
  @column()
  declare isActive: boolean
}

export class SocialLoginSchema extends BaseModel {
  static $columns = ['id', 'employeeId', 'provider', 'providerUserId', 'phone', 'isPrimary', 'lastLoginAt', 'profileData', 'createdAt'] as const
  $columns = SocialLoginSchema.$columns
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare employeeId: number
  @column()
  declare provider: string
  @column()
  declare providerUserId: string
  @column()
  declare phone: string | null
  @column()
  declare isPrimary: boolean
  @column.dateTime()
  declare lastLoginAt: DateTime | null
  @column()
  declare profileData: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
}

export class SubscriptionSchema extends BaseModel {
  static $columns = ['id', 'orgId', 'planId', 'status', 'billingCycle', 'startDate', 'endDate', 'trialStartDate', 'trialEndDate', 'graceEndDate', 'autoRenew', 'paymentGateway', 'externalSubscriptionId', 'metadata', 'createdAt', 'updatedAt'] as const
  $columns = SubscriptionSchema.$columns
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare orgId: number
  @column()
  declare planId: number | null
  @column()
  declare status: string
  @column()
  declare billingCycle: string
  @column.date()
  declare startDate: DateTime
  @column.date()
  declare endDate: DateTime | null
  @column.date()
  declare trialStartDate: DateTime | null
  @column.date()
  declare trialEndDate: DateTime | null
  @column.date()
  declare graceEndDate: DateTime | null
  @column()
  declare autoRenew: boolean
  @column()
  declare paymentGateway: string | null
  @column()
  declare externalSubscriptionId: string | null
  @column()
  declare metadata: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class TaskSchema extends BaseModel {
  static $columns = ['id', 'projectId', 'orgId', 'parentId', 'assignedTo', 'createdBy', 'title', 'description', 'priority', 'status', 'dueDate', 'estimatedHours', 'actualHours', 'deletedAt', 'createdAt', 'updatedAt'] as const
  $columns = TaskSchema.$columns
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare projectId: number
  @column()
  declare orgId: number
  @column()
  declare parentId: number | null
  @column()
  declare assignedTo: number | null
  @column()
  declare createdBy: number | null
  @column()
  declare title: string
  @column()
  declare description: string | null
  @column()
  declare priority: string
  @column()
  declare status: string
  @column.date()
  declare dueDate: DateTime | null
  @column()
  declare estimatedHours: string | null
  @column()
  declare actualHours: string | null
  @column.dateTime()
  declare deletedAt: DateTime | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class TimesheetSchema extends BaseModel {
  static $columns = ['id', 'employeeId', 'orgId', 'taskId', 'projectId', 'logDate', 'hoursLogged', 'description', 'createdAt'] as const
  $columns = TimesheetSchema.$columns
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare employeeId: number
  @column()
  declare orgId: number
  @column()
  declare taskId: number | null
  @column()
  declare projectId: number | null
  @column.date()
  declare logDate: DateTime
  @column()
  declare hoursLogged: string
  @column()
  declare description: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
}

export class TrustedDeviceSchema extends BaseModel {
  static $columns = ['id', 'employeeId', 'deviceId', 'deviceName', 'trustedAt', 'lastUsedAt'] as const
  $columns = TrustedDeviceSchema.$columns
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare employeeId: number
  @column()
  declare deviceId: string
  @column()
  declare deviceName: string | null
  @column.dateTime()
  declare trustedAt: DateTime
  @column.dateTime()
  declare lastUsedAt: DateTime | null
}

export class UserSchema extends BaseModel {
  static $columns = ['id', 'fullName', 'email', 'password', 'createdAt', 'updatedAt'] as const
  $columns = UserSchema.$columns
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare fullName: string | null
  @column()
  declare email: string
  @column({ serializeAs: null })
  declare password: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class UserPermissionSchema extends BaseModel {
  static $columns = ['id', 'employeeId', 'permissionId', 'effect', 'startsAt', 'endsAt', 'grantedBy', 'grantedAt', 'createdAt', 'updatedAt'] as const
  $columns = UserPermissionSchema.$columns
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare employeeId: number
  @column()
  declare permissionId: number
  @column()
  declare effect: string
  @column.dateTime()
  declare startsAt: DateTime | null
  @column.dateTime()
  declare endsAt: DateTime | null
  @column()
  declare grantedBy: number | null
  @column.dateTime()
  declare grantedAt: DateTime
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class UserSessionSchema extends BaseModel {
  static $columns = ['id', 'employeeId', 'orgId', 'sessionToken', 'refreshToken', 'deviceInfo', 'ipAddress', 'userAgent', 'lastActivity', 'expiresAt', 'isRevoked', 'revokedAt', 'revokedReason', 'createdAt'] as const
  $columns = UserSessionSchema.$columns
  @column({ isPrimary: true })
  declare id: bigint | number
  @column()
  declare employeeId: number
  @column()
  declare orgId: number
  @column()
  declare sessionToken: string
  @column()
  declare refreshToken: string | null
  @column()
  declare deviceInfo: string | null
  @column()
  declare ipAddress: string | null
  @column()
  declare userAgent: string | null
  @column.dateTime()
  declare lastActivity: DateTime
  @column.dateTime()
  declare expiresAt: DateTime
  @column()
  declare isRevoked: boolean
  @column.dateTime()
  declare revokedAt: DateTime | null
  @column()
  declare revokedReason: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
}

export class VisitSchema extends BaseModel {
  static $columns = ['id', 'orgId', 'clientId', 'visitorId', 'hostEmployeeId', 'createdBy', 'approverEmployeeId', 'approvedBy', 'title', 'purpose', 'locationName', 'visitType', 'priority', 'status', 'requiresApproval', 'scheduledStart', 'scheduledEnd', 'reminderAt', 'approvedAt', 'actualCheckInAt', 'actualCheckOutAt', 'checkInLatitude', 'checkInLongitude', 'checkOutLatitude', 'checkOutLongitude', 'checkInAddress', 'checkOutAddress', 'photoProofUrl', 'attachmentUrls', 'approvalNotes', 'completionNotes', 'createdAt', 'updatedAt'] as const
  $columns = VisitSchema.$columns
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare orgId: number
  @column()
  declare clientId: number | null
  @column()
  declare visitorId: number | null
  @column()
  declare hostEmployeeId: number | null
  @column()
  declare createdBy: number
  @column()
  declare approverEmployeeId: number | null
  @column()
  declare approvedBy: number | null
  @column()
  declare title: string
  @column()
  declare purpose: string
  @column()
  declare locationName: string | null
  @column()
  declare visitType: string
  @column()
  declare priority: string
  @column()
  declare status: string
  @column()
  declare requiresApproval: boolean
  @column.dateTime()
  declare scheduledStart: DateTime
  @column.dateTime()
  declare scheduledEnd: DateTime | null
  @column.dateTime()
  declare reminderAt: DateTime | null
  @column.dateTime()
  declare approvedAt: DateTime | null
  @column.dateTime()
  declare actualCheckInAt: DateTime | null
  @column.dateTime()
  declare actualCheckOutAt: DateTime | null
  @column()
  declare checkInLatitude: string | null
  @column()
  declare checkInLongitude: string | null
  @column()
  declare checkOutLatitude: string | null
  @column()
  declare checkOutLongitude: string | null
  @column()
  declare checkInAddress: string | null
  @column()
  declare checkOutAddress: string | null
  @column()
  declare photoProofUrl: string | null
  @column()
  declare attachmentUrls: string | null
  @column()
  declare approvalNotes: string | null
  @column()
  declare completionNotes: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class VisitClientSchema extends BaseModel {
  static $columns = ['id', 'orgId', 'name', 'industry', 'contactPerson', 'email', 'phone', 'address', 'isActive', 'createdAt', 'updatedAt'] as const
  $columns = VisitClientSchema.$columns
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare orgId: number
  @column()
  declare name: string
  @column()
  declare industry: string | null
  @column()
  declare contactPerson: string | null
  @column()
  declare email: string | null
  @column()
  declare phone: string | null
  @column()
  declare address: string | null
  @column()
  declare isActive: boolean
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class VisitFollowUpSchema extends BaseModel {
  static $columns = ['id', 'visitId', 'orgId', 'assignedTo', 'createdBy', 'status', 'priority', 'title', 'description', 'dueAt', 'completedAt', 'createdAt', 'updatedAt'] as const
  $columns = VisitFollowUpSchema.$columns
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare visitId: number
  @column()
  declare orgId: number
  @column()
  declare assignedTo: number | null
  @column()
  declare createdBy: number | null
  @column()
  declare status: string
  @column()
  declare priority: string
  @column()
  declare title: string
  @column()
  declare description: string | null
  @column.dateTime()
  declare dueAt: DateTime | null
  @column.dateTime()
  declare completedAt: DateTime | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class VisitNoteSchema extends BaseModel {
  static $columns = ['id', 'visitId', 'orgId', 'employeeId', 'noteType', 'content', 'attachmentUrls', 'photoProofUrl', 'createdAt'] as const
  $columns = VisitNoteSchema.$columns
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare visitId: number
  @column()
  declare orgId: number
  @column()
  declare employeeId: number | null
  @column()
  declare noteType: string
  @column()
  declare content: string
  @column()
  declare attachmentUrls: string | null
  @column()
  declare photoProofUrl: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
}

export class VisitVisitorSchema extends BaseModel {
  static $columns = ['id', 'orgId', 'clientId', 'fullName', 'email', 'phone', 'designation', 'address', 'notes', 'isActive', 'createdAt', 'updatedAt'] as const
  $columns = VisitVisitorSchema.$columns
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare orgId: number
  @column()
  declare clientId: number | null
  @column()
  declare fullName: string
  @column()
  declare email: string | null
  @column()
  declare phone: string | null
  @column()
  declare designation: string | null
  @column()
  declare address: string | null
  @column()
  declare notes: string | null
  @column()
  declare isActive: boolean
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}
