/**
 * This file is automatically generated.
 * DO NOT EDIT manually
 */

export const controllers = {
  AccessToken: () => import('#controllers/access_token_controller'),
  http: {
    Announcements: () => import('#controllers/Http/AnnouncementsController'),
    Attendances: () => import('#controllers/Http/AttendancesController'),
    AuditLogs: () => import('#controllers/Http/AuditLogsController'),
    Auth: () => import('#controllers/Http/AuthController'),
    Countries: () => import('#controllers/Http/CountriesController'),
    Documents: () => import('#controllers/Http/DocumentsController'),
    EmployeeEducations: () => import('#controllers/Http/EmployeeEducationsController'),
    EmployeeExperiences: () => import('#controllers/Http/EmployeeExperiencesController'),
    EmployeeInvitations: () => import('#controllers/Http/EmployeeInvitationsController'),
    Employees: () => import('#controllers/Http/EmployeesController'),
    EmployeeSelfService: () => import('#controllers/Http/EmployeeSelfServiceController'),
    Expenses: () => import('#controllers/Http/ExpensesController'),
    FaceRecognition: () => import('#controllers/Http/FaceRecognitionController'),
    Holidays: () => import('#controllers/Http/HolidaysController'),
    Leaves: () => import('#controllers/Http/LeavesController'),
    Notifications: () => import('#controllers/Http/NotificationsController'),
    Organizations: () => import('#controllers/Http/OrganizationsController'),
    Payrolls: () => import('#controllers/Http/PayrollsController'),
    Projects: () => import('#controllers/Http/ProjectsController'),
    Regularizations: () => import('#controllers/Http/RegularizationsController'),
    Reports: () => import('#controllers/Http/ReportsController'),
    Roles: () => import('#controllers/Http/RolesController'),
    SocialAuth: () => import('#controllers/Http/SocialAuthController'),
    Subscriptions: () => import('#controllers/Http/SubscriptionsController'),
    Timesheets: () => import('#controllers/Http/TimesheetsController'),
    Tracking: () => import('#controllers/Http/TrackingController'),
    VisitManagement: () => import('#controllers/Http/VisitManagementController'),
  },
  NewAccount: () => import('#controllers/new_account_controller'),
  OrgRegistration: () => import('#controllers/org_registration_controller'),
  Profile: () => import('#controllers/profile_controller'),
}
