/* eslint-disable prettier/prettier */
import type { AdonisEndpoint } from '@tuyau/core/types'
import type { Registry } from './schema.d.ts'
import type { ApiDefinition } from './tree.d.ts'

const placeholder: any = {}

const routes = {
  'countries.index': {
    methods: ["GET","HEAD"],
    pattern: '/api/auth/countries',
    tokens: [{"old":"/api/auth/countries","type":0,"val":"api","end":""},{"old":"/api/auth/countries","type":0,"val":"auth","end":""},{"old":"/api/auth/countries","type":0,"val":"countries","end":""}],
    types: placeholder as Registry['countries.index']['types'],
  },
  'org_registration.register': {
    methods: ["POST"],
    pattern: '/api/auth/register',
    tokens: [{"old":"/api/auth/register","type":0,"val":"api","end":""},{"old":"/api/auth/register","type":0,"val":"auth","end":""},{"old":"/api/auth/register","type":0,"val":"register","end":""}],
    types: placeholder as Registry['org_registration.register']['types'],
  },
  'org_registration.verify_email': {
    methods: ["GET","HEAD"],
    pattern: '/api/auth/verify-email',
    tokens: [{"old":"/api/auth/verify-email","type":0,"val":"api","end":""},{"old":"/api/auth/verify-email","type":0,"val":"auth","end":""},{"old":"/api/auth/verify-email","type":0,"val":"verify-email","end":""}],
    types: placeholder as Registry['org_registration.verify_email']['types'],
  },
  'auth.login': {
    methods: ["POST"],
    pattern: '/api/auth/login',
    tokens: [{"old":"/api/auth/login","type":0,"val":"api","end":""},{"old":"/api/auth/login","type":0,"val":"auth","end":""},{"old":"/api/auth/login","type":0,"val":"login","end":""}],
    types: placeholder as Registry['auth.login']['types'],
  },
  'auth.verify_otp': {
    methods: ["POST"],
    pattern: '/api/auth/verify-otp',
    tokens: [{"old":"/api/auth/verify-otp","type":0,"val":"api","end":""},{"old":"/api/auth/verify-otp","type":0,"val":"auth","end":""},{"old":"/api/auth/verify-otp","type":0,"val":"verify-otp","end":""}],
    types: placeholder as Registry['auth.verify_otp']['types'],
  },
  'auth.check_identifier': {
    methods: ["POST"],
    pattern: '/api/auth/check-identifier',
    tokens: [{"old":"/api/auth/check-identifier","type":0,"val":"api","end":""},{"old":"/api/auth/check-identifier","type":0,"val":"auth","end":""},{"old":"/api/auth/check-identifier","type":0,"val":"check-identifier","end":""}],
    types: placeholder as Registry['auth.check_identifier']['types'],
  },
  'auth.request_email_otp': {
    methods: ["POST"],
    pattern: '/api/auth/request-email-otp',
    tokens: [{"old":"/api/auth/request-email-otp","type":0,"val":"api","end":""},{"old":"/api/auth/request-email-otp","type":0,"val":"auth","end":""},{"old":"/api/auth/request-email-otp","type":0,"val":"request-email-otp","end":""}],
    types: placeholder as Registry['auth.request_email_otp']['types'],
  },
  'auth.verify_email_otp': {
    methods: ["POST"],
    pattern: '/api/auth/verify-email-otp',
    tokens: [{"old":"/api/auth/verify-email-otp","type":0,"val":"api","end":""},{"old":"/api/auth/verify-email-otp","type":0,"val":"auth","end":""},{"old":"/api/auth/verify-email-otp","type":0,"val":"verify-email-otp","end":""}],
    types: placeholder as Registry['auth.verify_email_otp']['types'],
  },
  'auth.login_with_verified_email': {
    methods: ["POST"],
    pattern: '/api/auth/login-with-verified-email',
    tokens: [{"old":"/api/auth/login-with-verified-email","type":0,"val":"api","end":""},{"old":"/api/auth/login-with-verified-email","type":0,"val":"auth","end":""},{"old":"/api/auth/login-with-verified-email","type":0,"val":"login-with-verified-email","end":""}],
    types: placeholder as Registry['auth.login_with_verified_email']['types'],
  },
  'auth.forgot_password': {
    methods: ["POST"],
    pattern: '/api/auth/forgot-password',
    tokens: [{"old":"/api/auth/forgot-password","type":0,"val":"api","end":""},{"old":"/api/auth/forgot-password","type":0,"val":"auth","end":""},{"old":"/api/auth/forgot-password","type":0,"val":"forgot-password","end":""}],
    types: placeholder as Registry['auth.forgot_password']['types'],
  },
  'auth.reset_password': {
    methods: ["POST"],
    pattern: '/api/auth/reset-password',
    tokens: [{"old":"/api/auth/reset-password","type":0,"val":"api","end":""},{"old":"/api/auth/reset-password","type":0,"val":"auth","end":""},{"old":"/api/auth/reset-password","type":0,"val":"reset-password","end":""}],
    types: placeholder as Registry['auth.reset_password']['types'],
  },
  'auth.logout': {
    methods: ["POST"],
    pattern: '/api/auth/logout',
    tokens: [{"old":"/api/auth/logout","type":0,"val":"api","end":""},{"old":"/api/auth/logout","type":0,"val":"auth","end":""},{"old":"/api/auth/logout","type":0,"val":"logout","end":""}],
    types: placeholder as Registry['auth.logout']['types'],
  },
  'auth.me': {
    methods: ["GET","HEAD"],
    pattern: '/api/auth/me',
    tokens: [{"old":"/api/auth/me","type":0,"val":"api","end":""},{"old":"/api/auth/me","type":0,"val":"auth","end":""},{"old":"/api/auth/me","type":0,"val":"me","end":""}],
    types: placeholder as Registry['auth.me']['types'],
  },
  'social_auth.redirect_to_google': {
    methods: ["GET","HEAD"],
    pattern: '/api/auth/google',
    tokens: [{"old":"/api/auth/google","type":0,"val":"api","end":""},{"old":"/api/auth/google","type":0,"val":"auth","end":""},{"old":"/api/auth/google","type":0,"val":"google","end":""}],
    types: placeholder as Registry['social_auth.redirect_to_google']['types'],
  },
  'social_auth.handle_google_callback': {
    methods: ["GET","HEAD"],
    pattern: '/api/auth/google/callback',
    tokens: [{"old":"/api/auth/google/callback","type":0,"val":"api","end":""},{"old":"/api/auth/google/callback","type":0,"val":"auth","end":""},{"old":"/api/auth/google/callback","type":0,"val":"google","end":""},{"old":"/api/auth/google/callback","type":0,"val":"callback","end":""}],
    types: placeholder as Registry['social_auth.handle_google_callback']['types'],
  },
  'social_auth.redirect_to_microsoft': {
    methods: ["GET","HEAD"],
    pattern: '/api/auth/microsoft',
    tokens: [{"old":"/api/auth/microsoft","type":0,"val":"api","end":""},{"old":"/api/auth/microsoft","type":0,"val":"auth","end":""},{"old":"/api/auth/microsoft","type":0,"val":"microsoft","end":""}],
    types: placeholder as Registry['social_auth.redirect_to_microsoft']['types'],
  },
  'social_auth.handle_microsoft_callback': {
    methods: ["GET","HEAD"],
    pattern: '/api/auth/microsoft/callback',
    tokens: [{"old":"/api/auth/microsoft/callback","type":0,"val":"api","end":""},{"old":"/api/auth/microsoft/callback","type":0,"val":"auth","end":""},{"old":"/api/auth/microsoft/callback","type":0,"val":"microsoft","end":""},{"old":"/api/auth/microsoft/callback","type":0,"val":"callback","end":""}],
    types: placeholder as Registry['social_auth.handle_microsoft_callback']['types'],
  },
  'social_auth.request_phone_otp': {
    methods: ["POST"],
    pattern: '/api/auth/phone/request-otp',
    tokens: [{"old":"/api/auth/phone/request-otp","type":0,"val":"api","end":""},{"old":"/api/auth/phone/request-otp","type":0,"val":"auth","end":""},{"old":"/api/auth/phone/request-otp","type":0,"val":"phone","end":""},{"old":"/api/auth/phone/request-otp","type":0,"val":"request-otp","end":""}],
    types: placeholder as Registry['social_auth.request_phone_otp']['types'],
  },
  'social_auth.verify_phone_otp': {
    methods: ["POST"],
    pattern: '/api/auth/phone/verify',
    tokens: [{"old":"/api/auth/phone/verify","type":0,"val":"api","end":""},{"old":"/api/auth/phone/verify","type":0,"val":"auth","end":""},{"old":"/api/auth/phone/verify","type":0,"val":"phone","end":""},{"old":"/api/auth/phone/verify","type":0,"val":"verify","end":""}],
    types: placeholder as Registry['social_auth.verify_phone_otp']['types'],
  },
  'social_auth.resend_phone_otp': {
    methods: ["POST"],
    pattern: '/api/auth/phone/resend',
    tokens: [{"old":"/api/auth/phone/resend","type":0,"val":"api","end":""},{"old":"/api/auth/phone/resend","type":0,"val":"auth","end":""},{"old":"/api/auth/phone/resend","type":0,"val":"phone","end":""},{"old":"/api/auth/phone/resend","type":0,"val":"resend","end":""}],
    types: placeholder as Registry['social_auth.resend_phone_otp']['types'],
  },
  'social_auth.enable_phone_auth': {
    methods: ["POST"],
    pattern: '/api/auth/phone/enable',
    tokens: [{"old":"/api/auth/phone/enable","type":0,"val":"api","end":""},{"old":"/api/auth/phone/enable","type":0,"val":"auth","end":""},{"old":"/api/auth/phone/enable","type":0,"val":"phone","end":""},{"old":"/api/auth/phone/enable","type":0,"val":"enable","end":""}],
    types: placeholder as Registry['social_auth.enable_phone_auth']['types'],
  },
  'social_auth.disable_phone_auth': {
    methods: ["POST"],
    pattern: '/api/auth/phone/disable',
    tokens: [{"old":"/api/auth/phone/disable","type":0,"val":"api","end":""},{"old":"/api/auth/phone/disable","type":0,"val":"auth","end":""},{"old":"/api/auth/phone/disable","type":0,"val":"phone","end":""},{"old":"/api/auth/phone/disable","type":0,"val":"disable","end":""}],
    types: placeholder as Registry['social_auth.disable_phone_auth']['types'],
  },
  'social_auth.link_social_account': {
    methods: ["POST"],
    pattern: '/api/auth/social/link',
    tokens: [{"old":"/api/auth/social/link","type":0,"val":"api","end":""},{"old":"/api/auth/social/link","type":0,"val":"auth","end":""},{"old":"/api/auth/social/link","type":0,"val":"social","end":""},{"old":"/api/auth/social/link","type":0,"val":"link","end":""}],
    types: placeholder as Registry['social_auth.link_social_account']['types'],
  },
  'organizations.show': {
    methods: ["GET","HEAD"],
    pattern: '/api/organization',
    tokens: [{"old":"/api/organization","type":0,"val":"api","end":""},{"old":"/api/organization","type":0,"val":"organization","end":""}],
    types: placeholder as Registry['organizations.show']['types'],
  },
  'organizations.update': {
    methods: ["PUT"],
    pattern: '/api/organization',
    tokens: [{"old":"/api/organization","type":0,"val":"api","end":""},{"old":"/api/organization","type":0,"val":"organization","end":""}],
    types: placeholder as Registry['organizations.update']['types'],
  },
  'organizations.get_departments': {
    methods: ["GET","HEAD"],
    pattern: '/api/organization/departments',
    tokens: [{"old":"/api/organization/departments","type":0,"val":"api","end":""},{"old":"/api/organization/departments","type":0,"val":"organization","end":""},{"old":"/api/organization/departments","type":0,"val":"departments","end":""}],
    types: placeholder as Registry['organizations.get_departments']['types'],
  },
  'organizations.store_department': {
    methods: ["POST"],
    pattern: '/api/organization/departments',
    tokens: [{"old":"/api/organization/departments","type":0,"val":"api","end":""},{"old":"/api/organization/departments","type":0,"val":"organization","end":""},{"old":"/api/organization/departments","type":0,"val":"departments","end":""}],
    types: placeholder as Registry['organizations.store_department']['types'],
  },
  'organizations.update_department': {
    methods: ["PUT"],
    pattern: '/api/organization/departments/:id',
    tokens: [{"old":"/api/organization/departments/:id","type":0,"val":"api","end":""},{"old":"/api/organization/departments/:id","type":0,"val":"organization","end":""},{"old":"/api/organization/departments/:id","type":0,"val":"departments","end":""},{"old":"/api/organization/departments/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['organizations.update_department']['types'],
  },
  'organizations.destroy_department': {
    methods: ["DELETE"],
    pattern: '/api/organization/departments/:id',
    tokens: [{"old":"/api/organization/departments/:id","type":0,"val":"api","end":""},{"old":"/api/organization/departments/:id","type":0,"val":"organization","end":""},{"old":"/api/organization/departments/:id","type":0,"val":"departments","end":""},{"old":"/api/organization/departments/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['organizations.destroy_department']['types'],
  },
  'organizations.get_designations': {
    methods: ["GET","HEAD"],
    pattern: '/api/organization/designations',
    tokens: [{"old":"/api/organization/designations","type":0,"val":"api","end":""},{"old":"/api/organization/designations","type":0,"val":"organization","end":""},{"old":"/api/organization/designations","type":0,"val":"designations","end":""}],
    types: placeholder as Registry['organizations.get_designations']['types'],
  },
  'organizations.store_designation': {
    methods: ["POST"],
    pattern: '/api/organization/designations',
    tokens: [{"old":"/api/organization/designations","type":0,"val":"api","end":""},{"old":"/api/organization/designations","type":0,"val":"organization","end":""},{"old":"/api/organization/designations","type":0,"val":"designations","end":""}],
    types: placeholder as Registry['organizations.store_designation']['types'],
  },
  'organizations.update_designation': {
    methods: ["PUT"],
    pattern: '/api/organization/designations/:id',
    tokens: [{"old":"/api/organization/designations/:id","type":0,"val":"api","end":""},{"old":"/api/organization/designations/:id","type":0,"val":"organization","end":""},{"old":"/api/organization/designations/:id","type":0,"val":"designations","end":""},{"old":"/api/organization/designations/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['organizations.update_designation']['types'],
  },
  'organizations.destroy_designation': {
    methods: ["DELETE"],
    pattern: '/api/organization/designations/:id',
    tokens: [{"old":"/api/organization/designations/:id","type":0,"val":"api","end":""},{"old":"/api/organization/designations/:id","type":0,"val":"organization","end":""},{"old":"/api/organization/designations/:id","type":0,"val":"designations","end":""},{"old":"/api/organization/designations/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['organizations.destroy_designation']['types'],
  },
  'organizations.get_setting_collection': {
    methods: ["GET","HEAD"],
    pattern: '/api/organization/settings/:key',
    tokens: [{"old":"/api/organization/settings/:key","type":0,"val":"api","end":""},{"old":"/api/organization/settings/:key","type":0,"val":"organization","end":""},{"old":"/api/organization/settings/:key","type":0,"val":"settings","end":""},{"old":"/api/organization/settings/:key","type":1,"val":"key","end":""}],
    types: placeholder as Registry['organizations.get_setting_collection']['types'],
  },
  'organizations.save_setting_collection': {
    methods: ["PUT"],
    pattern: '/api/organization/settings/:key',
    tokens: [{"old":"/api/organization/settings/:key","type":0,"val":"api","end":""},{"old":"/api/organization/settings/:key","type":0,"val":"organization","end":""},{"old":"/api/organization/settings/:key","type":0,"val":"settings","end":""},{"old":"/api/organization/settings/:key","type":1,"val":"key","end":""}],
    types: placeholder as Registry['organizations.save_setting_collection']['types'],
  },
  'holidays.index': {
    methods: ["GET","HEAD"],
    pattern: '/api/organization/holidays',
    tokens: [{"old":"/api/organization/holidays","type":0,"val":"api","end":""},{"old":"/api/organization/holidays","type":0,"val":"organization","end":""},{"old":"/api/organization/holidays","type":0,"val":"holidays","end":""}],
    types: placeholder as Registry['holidays.index']['types'],
  },
  'holidays.store': {
    methods: ["POST"],
    pattern: '/api/organization/holidays',
    tokens: [{"old":"/api/organization/holidays","type":0,"val":"api","end":""},{"old":"/api/organization/holidays","type":0,"val":"organization","end":""},{"old":"/api/organization/holidays","type":0,"val":"holidays","end":""}],
    types: placeholder as Registry['holidays.store']['types'],
  },
  'holidays.update': {
    methods: ["PUT"],
    pattern: '/api/organization/holidays/:id',
    tokens: [{"old":"/api/organization/holidays/:id","type":0,"val":"api","end":""},{"old":"/api/organization/holidays/:id","type":0,"val":"organization","end":""},{"old":"/api/organization/holidays/:id","type":0,"val":"holidays","end":""},{"old":"/api/organization/holidays/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['holidays.update']['types'],
  },
  'holidays.destroy': {
    methods: ["DELETE"],
    pattern: '/api/organization/holidays/:id',
    tokens: [{"old":"/api/organization/holidays/:id","type":0,"val":"api","end":""},{"old":"/api/organization/holidays/:id","type":0,"val":"organization","end":""},{"old":"/api/organization/holidays/:id","type":0,"val":"holidays","end":""},{"old":"/api/organization/holidays/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['holidays.destroy']['types'],
  },
  'organizations.get_addons': {
    methods: ["GET","HEAD"],
    pattern: '/api/organization/addons',
    tokens: [{"old":"/api/organization/addons","type":0,"val":"api","end":""},{"old":"/api/organization/addons","type":0,"val":"organization","end":""},{"old":"/api/organization/addons","type":0,"val":"addons","end":""}],
    types: placeholder as Registry['organizations.get_addons']['types'],
  },
  'organizations.toggle_addon': {
    methods: ["POST"],
    pattern: '/api/organization/addons/toggle',
    tokens: [{"old":"/api/organization/addons/toggle","type":0,"val":"api","end":""},{"old":"/api/organization/addons/toggle","type":0,"val":"organization","end":""},{"old":"/api/organization/addons/toggle","type":0,"val":"addons","end":""},{"old":"/api/organization/addons/toggle","type":0,"val":"toggle","end":""}],
    types: placeholder as Registry['organizations.toggle_addon']['types'],
  },
  'employees.index': {
    methods: ["GET","HEAD"],
    pattern: '/api/employees',
    tokens: [{"old":"/api/employees","type":0,"val":"api","end":""},{"old":"/api/employees","type":0,"val":"employees","end":""}],
    types: placeholder as Registry['employees.index']['types'],
  },
  'employees.store': {
    methods: ["POST"],
    pattern: '/api/employees',
    tokens: [{"old":"/api/employees","type":0,"val":"api","end":""},{"old":"/api/employees","type":0,"val":"employees","end":""}],
    types: placeholder as Registry['employees.store']['types'],
  },
  'employees.occasions': {
    methods: ["GET","HEAD"],
    pattern: '/api/employees/occasions',
    tokens: [{"old":"/api/employees/occasions","type":0,"val":"api","end":""},{"old":"/api/employees/occasions","type":0,"val":"employees","end":""},{"old":"/api/employees/occasions","type":0,"val":"occasions","end":""}],
    types: placeholder as Registry['employees.occasions']['types'],
  },
  'employees.show': {
    methods: ["GET","HEAD"],
    pattern: '/api/employees/:id',
    tokens: [{"old":"/api/employees/:id","type":0,"val":"api","end":""},{"old":"/api/employees/:id","type":0,"val":"employees","end":""},{"old":"/api/employees/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['employees.show']['types'],
  },
  'employees.update': {
    methods: ["PUT"],
    pattern: '/api/employees/:id',
    tokens: [{"old":"/api/employees/:id","type":0,"val":"api","end":""},{"old":"/api/employees/:id","type":0,"val":"employees","end":""},{"old":"/api/employees/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['employees.update']['types'],
  },
  'employees.destroy': {
    methods: ["DELETE"],
    pattern: '/api/employees/:id',
    tokens: [{"old":"/api/employees/:id","type":0,"val":"api","end":""},{"old":"/api/employees/:id","type":0,"val":"employees","end":""},{"old":"/api/employees/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['employees.destroy']['types'],
  },
  'employees.update_geofence': {
    methods: ["PUT"],
    pattern: '/api/employees/:id/geofence',
    tokens: [{"old":"/api/employees/:id/geofence","type":0,"val":"api","end":""},{"old":"/api/employees/:id/geofence","type":0,"val":"employees","end":""},{"old":"/api/employees/:id/geofence","type":1,"val":"id","end":""},{"old":"/api/employees/:id/geofence","type":0,"val":"geofence","end":""}],
    types: placeholder as Registry['employees.update_geofence']['types'],
  },
  'employees.get_geofence': {
    methods: ["GET","HEAD"],
    pattern: '/api/employees/:id/geofence',
    tokens: [{"old":"/api/employees/:id/geofence","type":0,"val":"api","end":""},{"old":"/api/employees/:id/geofence","type":0,"val":"employees","end":""},{"old":"/api/employees/:id/geofence","type":1,"val":"id","end":""},{"old":"/api/employees/:id/geofence","type":0,"val":"geofence","end":""}],
    types: placeholder as Registry['employees.get_geofence']['types'],
  },
  'employees.remove_geofence': {
    methods: ["DELETE"],
    pattern: '/api/employees/:id/geofence',
    tokens: [{"old":"/api/employees/:id/geofence","type":0,"val":"api","end":""},{"old":"/api/employees/:id/geofence","type":0,"val":"employees","end":""},{"old":"/api/employees/:id/geofence","type":1,"val":"id","end":""},{"old":"/api/employees/:id/geofence","type":0,"val":"geofence","end":""}],
    types: placeholder as Registry['employees.remove_geofence']['types'],
  },
  'subscriptions.list_plans': {
    methods: ["GET","HEAD"],
    pattern: '/api/billing/plans',
    tokens: [{"old":"/api/billing/plans","type":0,"val":"api","end":""},{"old":"/api/billing/plans","type":0,"val":"billing","end":""},{"old":"/api/billing/plans","type":0,"val":"plans","end":""}],
    types: placeholder as Registry['subscriptions.list_plans']['types'],
  },
  'subscriptions.razorpay_webhook': {
    methods: ["POST"],
    pattern: '/api/billing/webhooks/razorpay',
    tokens: [{"old":"/api/billing/webhooks/razorpay","type":0,"val":"api","end":""},{"old":"/api/billing/webhooks/razorpay","type":0,"val":"billing","end":""},{"old":"/api/billing/webhooks/razorpay","type":0,"val":"webhooks","end":""},{"old":"/api/billing/webhooks/razorpay","type":0,"val":"razorpay","end":""}],
    types: placeholder as Registry['subscriptions.razorpay_webhook']['types'],
  },
  'subscriptions.stripe_webhook': {
    methods: ["POST"],
    pattern: '/api/billing/webhooks/stripe',
    tokens: [{"old":"/api/billing/webhooks/stripe","type":0,"val":"api","end":""},{"old":"/api/billing/webhooks/stripe","type":0,"val":"billing","end":""},{"old":"/api/billing/webhooks/stripe","type":0,"val":"webhooks","end":""},{"old":"/api/billing/webhooks/stripe","type":0,"val":"stripe","end":""}],
    types: placeholder as Registry['subscriptions.stripe_webhook']['types'],
  },
  'subscriptions.legacy_invoice': {
    methods: ["GET","HEAD"],
    pattern: '/api/billing/legacy/invoice',
    tokens: [{"old":"/api/billing/legacy/invoice","type":0,"val":"api","end":""},{"old":"/api/billing/legacy/invoice","type":0,"val":"billing","end":""},{"old":"/api/billing/legacy/invoice","type":0,"val":"legacy","end":""},{"old":"/api/billing/legacy/invoice","type":0,"val":"invoice","end":""}],
    types: placeholder as Registry['subscriptions.legacy_invoice']['types'],
  },
  'subscriptions.get_status': {
    methods: ["GET","HEAD"],
    pattern: '/api/billing/status',
    tokens: [{"old":"/api/billing/status","type":0,"val":"api","end":""},{"old":"/api/billing/status","type":0,"val":"billing","end":""},{"old":"/api/billing/status","type":0,"val":"status","end":""}],
    types: placeholder as Registry['subscriptions.get_status']['types'],
  },
  'subscriptions.create_upgrade_intent': {
    methods: ["POST"],
    pattern: '/api/billing/upgrade-intent',
    tokens: [{"old":"/api/billing/upgrade-intent","type":0,"val":"api","end":""},{"old":"/api/billing/upgrade-intent","type":0,"val":"billing","end":""},{"old":"/api/billing/upgrade-intent","type":0,"val":"upgrade-intent","end":""}],
    types: placeholder as Registry['subscriptions.create_upgrade_intent']['types'],
  },
  'subscriptions.verify_payment': {
    methods: ["POST"],
    pattern: '/api/billing/verify-payment',
    tokens: [{"old":"/api/billing/verify-payment","type":0,"val":"api","end":""},{"old":"/api/billing/verify-payment","type":0,"val":"billing","end":""},{"old":"/api/billing/verify-payment","type":0,"val":"verify-payment","end":""}],
    types: placeholder as Registry['subscriptions.verify_payment']['types'],
  },
  'subscriptions.get_legacy_context': {
    methods: ["GET","HEAD"],
    pattern: '/api/billing/legacy/context',
    tokens: [{"old":"/api/billing/legacy/context","type":0,"val":"api","end":""},{"old":"/api/billing/legacy/context","type":0,"val":"billing","end":""},{"old":"/api/billing/legacy/context","type":0,"val":"legacy","end":""},{"old":"/api/billing/legacy/context","type":0,"val":"context","end":""}],
    types: placeholder as Registry['subscriptions.get_legacy_context']['types'],
  },
  'subscriptions.legacy_purchase': {
    methods: ["POST"],
    pattern: '/api/billing/legacy/purchase',
    tokens: [{"old":"/api/billing/legacy/purchase","type":0,"val":"api","end":""},{"old":"/api/billing/legacy/purchase","type":0,"val":"billing","end":""},{"old":"/api/billing/legacy/purchase","type":0,"val":"legacy","end":""},{"old":"/api/billing/legacy/purchase","type":0,"val":"purchase","end":""}],
    types: placeholder as Registry['subscriptions.legacy_purchase']['types'],
  },
  'subscriptions.legacy_confirm': {
    methods: ["POST"],
    pattern: '/api/billing/legacy/confirm',
    tokens: [{"old":"/api/billing/legacy/confirm","type":0,"val":"api","end":""},{"old":"/api/billing/legacy/confirm","type":0,"val":"billing","end":""},{"old":"/api/billing/legacy/confirm","type":0,"val":"legacy","end":""},{"old":"/api/billing/legacy/confirm","type":0,"val":"confirm","end":""}],
    types: placeholder as Registry['subscriptions.legacy_confirm']['types'],
  },
  'attendances.check_in': {
    methods: ["POST"],
    pattern: '/api/attendance/check-in',
    tokens: [{"old":"/api/attendance/check-in","type":0,"val":"api","end":""},{"old":"/api/attendance/check-in","type":0,"val":"attendance","end":""},{"old":"/api/attendance/check-in","type":0,"val":"check-in","end":""}],
    types: placeholder as Registry['attendances.check_in']['types'],
  },
  'attendances.check_out': {
    methods: ["POST"],
    pattern: '/api/attendance/check-out',
    tokens: [{"old":"/api/attendance/check-out","type":0,"val":"api","end":""},{"old":"/api/attendance/check-out","type":0,"val":"attendance","end":""},{"old":"/api/attendance/check-out","type":0,"val":"check-out","end":""}],
    types: placeholder as Registry['attendances.check_out']['types'],
  },
  'attendances.history': {
    methods: ["GET","HEAD"],
    pattern: '/api/attendance/history',
    tokens: [{"old":"/api/attendance/history","type":0,"val":"api","end":""},{"old":"/api/attendance/history","type":0,"val":"attendance","end":""},{"old":"/api/attendance/history","type":0,"val":"history","end":""}],
    types: placeholder as Registry['attendances.history']['types'],
  },
  'attendances.get_today': {
    methods: ["GET","HEAD"],
    pattern: '/api/attendance/today',
    tokens: [{"old":"/api/attendance/today","type":0,"val":"api","end":""},{"old":"/api/attendance/today","type":0,"val":"attendance","end":""},{"old":"/api/attendance/today","type":0,"val":"today","end":""}],
    types: placeholder as Registry['attendances.get_today']['types'],
  },
  'attendances.start_break': {
    methods: ["POST"],
    pattern: '/api/attendance/break/start',
    tokens: [{"old":"/api/attendance/break/start","type":0,"val":"api","end":""},{"old":"/api/attendance/break/start","type":0,"val":"attendance","end":""},{"old":"/api/attendance/break/start","type":0,"val":"break","end":""},{"old":"/api/attendance/break/start","type":0,"val":"start","end":""}],
    types: placeholder as Registry['attendances.start_break']['types'],
  },
  'attendances.end_break': {
    methods: ["POST"],
    pattern: '/api/attendance/break/end',
    tokens: [{"old":"/api/attendance/break/end","type":0,"val":"api","end":""},{"old":"/api/attendance/break/end","type":0,"val":"attendance","end":""},{"old":"/api/attendance/break/end","type":0,"val":"break","end":""},{"old":"/api/attendance/break/end","type":0,"val":"end","end":""}],
    types: placeholder as Registry['attendances.end_break']['types'],
  },
  'attendances.get_today_breaks': {
    methods: ["GET","HEAD"],
    pattern: '/api/attendance/breaks/today',
    tokens: [{"old":"/api/attendance/breaks/today","type":0,"val":"api","end":""},{"old":"/api/attendance/breaks/today","type":0,"val":"attendance","end":""},{"old":"/api/attendance/breaks/today","type":0,"val":"breaks","end":""},{"old":"/api/attendance/breaks/today","type":0,"val":"today","end":""}],
    types: placeholder as Registry['attendances.get_today_breaks']['types'],
  },
  'attendances.get_stats': {
    methods: ["GET","HEAD"],
    pattern: '/api/attendance/stats',
    tokens: [{"old":"/api/attendance/stats","type":0,"val":"api","end":""},{"old":"/api/attendance/stats","type":0,"val":"attendance","end":""},{"old":"/api/attendance/stats","type":0,"val":"stats","end":""}],
    types: placeholder as Registry['attendances.get_stats']['types'],
  },
  'attendances.get_monthly': {
    methods: ["GET","HEAD"],
    pattern: '/api/attendance/monthly',
    tokens: [{"old":"/api/attendance/monthly","type":0,"val":"api","end":""},{"old":"/api/attendance/monthly","type":0,"val":"attendance","end":""},{"old":"/api/attendance/monthly","type":0,"val":"monthly","end":""}],
    types: placeholder as Registry['attendances.get_monthly']['types'],
  },
  'attendances.request_manual': {
    methods: ["POST"],
    pattern: '/api/attendance/manual/request',
    tokens: [{"old":"/api/attendance/manual/request","type":0,"val":"api","end":""},{"old":"/api/attendance/manual/request","type":0,"val":"attendance","end":""},{"old":"/api/attendance/manual/request","type":0,"val":"manual","end":""},{"old":"/api/attendance/manual/request","type":0,"val":"request","end":""}],
    types: placeholder as Registry['attendances.request_manual']['types'],
  },
  'attendances.get_manual_requests': {
    methods: ["GET","HEAD"],
    pattern: '/api/attendance/manual/requests',
    tokens: [{"old":"/api/attendance/manual/requests","type":0,"val":"api","end":""},{"old":"/api/attendance/manual/requests","type":0,"val":"attendance","end":""},{"old":"/api/attendance/manual/requests","type":0,"val":"manual","end":""},{"old":"/api/attendance/manual/requests","type":0,"val":"requests","end":""}],
    types: placeholder as Registry['attendances.get_manual_requests']['types'],
  },
  'attendances.process_manual': {
    methods: ["POST"],
    pattern: '/api/attendance/manual/process',
    tokens: [{"old":"/api/attendance/manual/process","type":0,"val":"api","end":""},{"old":"/api/attendance/manual/process","type":0,"val":"attendance","end":""},{"old":"/api/attendance/manual/process","type":0,"val":"manual","end":""},{"old":"/api/attendance/manual/process","type":0,"val":"process","end":""}],
    types: placeholder as Registry['attendances.process_manual']['types'],
  },
  'attendances.request_overtime': {
    methods: ["POST"],
    pattern: '/api/attendance/overtime/request',
    tokens: [{"old":"/api/attendance/overtime/request","type":0,"val":"api","end":""},{"old":"/api/attendance/overtime/request","type":0,"val":"attendance","end":""},{"old":"/api/attendance/overtime/request","type":0,"val":"overtime","end":""},{"old":"/api/attendance/overtime/request","type":0,"val":"request","end":""}],
    types: placeholder as Registry['attendances.request_overtime']['types'],
  },
  'attendances.get_overtime': {
    methods: ["GET","HEAD"],
    pattern: '/api/attendance/overtime',
    tokens: [{"old":"/api/attendance/overtime","type":0,"val":"api","end":""},{"old":"/api/attendance/overtime","type":0,"val":"attendance","end":""},{"old":"/api/attendance/overtime","type":0,"val":"overtime","end":""}],
    types: placeholder as Registry['attendances.get_overtime']['types'],
  },
  'attendances.validate_location': {
    methods: ["GET","HEAD"],
    pattern: '/api/attendance/validate-location',
    tokens: [{"old":"/api/attendance/validate-location","type":0,"val":"api","end":""},{"old":"/api/attendance/validate-location","type":0,"val":"attendance","end":""},{"old":"/api/attendance/validate-location","type":0,"val":"validate-location","end":""}],
    types: placeholder as Registry['attendances.validate_location']['types'],
  },
  'attendances.get_zones': {
    methods: ["GET","HEAD"],
    pattern: '/api/attendance/zones',
    tokens: [{"old":"/api/attendance/zones","type":0,"val":"api","end":""},{"old":"/api/attendance/zones","type":0,"val":"attendance","end":""},{"old":"/api/attendance/zones","type":0,"val":"zones","end":""}],
    types: placeholder as Registry['attendances.get_zones']['types'],
  },
  'attendances.create_zone': {
    methods: ["POST"],
    pattern: '/api/attendance/zones',
    tokens: [{"old":"/api/attendance/zones","type":0,"val":"api","end":""},{"old":"/api/attendance/zones","type":0,"val":"attendance","end":""},{"old":"/api/attendance/zones","type":0,"val":"zones","end":""}],
    types: placeholder as Registry['attendances.create_zone']['types'],
  },
  'attendances.update_zone': {
    methods: ["PUT"],
    pattern: '/api/attendance/zones/:id',
    tokens: [{"old":"/api/attendance/zones/:id","type":0,"val":"api","end":""},{"old":"/api/attendance/zones/:id","type":0,"val":"attendance","end":""},{"old":"/api/attendance/zones/:id","type":0,"val":"zones","end":""},{"old":"/api/attendance/zones/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['attendances.update_zone']['types'],
  },
  'attendances.delete_zone': {
    methods: ["DELETE"],
    pattern: '/api/attendance/zones/:id',
    tokens: [{"old":"/api/attendance/zones/:id","type":0,"val":"api","end":""},{"old":"/api/attendance/zones/:id","type":0,"val":"attendance","end":""},{"old":"/api/attendance/zones/:id","type":0,"val":"zones","end":""},{"old":"/api/attendance/zones/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['attendances.delete_zone']['types'],
  },
  'attendances.get_geo_fence_settings': {
    methods: ["GET","HEAD"],
    pattern: '/api/attendance/geofence-settings',
    tokens: [{"old":"/api/attendance/geofence-settings","type":0,"val":"api","end":""},{"old":"/api/attendance/geofence-settings","type":0,"val":"attendance","end":""},{"old":"/api/attendance/geofence-settings","type":0,"val":"geofence-settings","end":""}],
    types: placeholder as Registry['attendances.get_geo_fence_settings']['types'],
  },
  'attendances.update_geo_fence_settings': {
    methods: ["PUT"],
    pattern: '/api/attendance/geofence-settings',
    tokens: [{"old":"/api/attendance/geofence-settings","type":0,"val":"api","end":""},{"old":"/api/attendance/geofence-settings","type":0,"val":"attendance","end":""},{"old":"/api/attendance/geofence-settings","type":0,"val":"geofence-settings","end":""}],
    types: placeholder as Registry['attendances.update_geo_fence_settings']['types'],
  },
  'attendances.get_all': {
    methods: ["GET","HEAD"],
    pattern: '/api/attendance/all',
    tokens: [{"old":"/api/attendance/all","type":0,"val":"api","end":""},{"old":"/api/attendance/all","type":0,"val":"attendance","end":""},{"old":"/api/attendance/all","type":0,"val":"all","end":""}],
    types: placeholder as Registry['attendances.get_all']['types'],
  },
  'attendances.get_today_all': {
    methods: ["GET","HEAD"],
    pattern: '/api/attendance/all/today',
    tokens: [{"old":"/api/attendance/all/today","type":0,"val":"api","end":""},{"old":"/api/attendance/all/today","type":0,"val":"attendance","end":""},{"old":"/api/attendance/all/today","type":0,"val":"all","end":""},{"old":"/api/attendance/all/today","type":0,"val":"today","end":""}],
    types: placeholder as Registry['attendances.get_today_all']['types'],
  },
  'attendances.get_shifts': {
    methods: ["GET","HEAD"],
    pattern: '/api/attendance/shifts',
    tokens: [{"old":"/api/attendance/shifts","type":0,"val":"api","end":""},{"old":"/api/attendance/shifts","type":0,"val":"attendance","end":""},{"old":"/api/attendance/shifts","type":0,"val":"shifts","end":""}],
    types: placeholder as Registry['attendances.get_shifts']['types'],
  },
  'attendances.create_shift': {
    methods: ["POST"],
    pattern: '/api/attendance/shifts',
    tokens: [{"old":"/api/attendance/shifts","type":0,"val":"api","end":""},{"old":"/api/attendance/shifts","type":0,"val":"attendance","end":""},{"old":"/api/attendance/shifts","type":0,"val":"shifts","end":""}],
    types: placeholder as Registry['attendances.create_shift']['types'],
  },
  'attendances.update_shift': {
    methods: ["PUT"],
    pattern: '/api/attendance/shifts/:id',
    tokens: [{"old":"/api/attendance/shifts/:id","type":0,"val":"api","end":""},{"old":"/api/attendance/shifts/:id","type":0,"val":"attendance","end":""},{"old":"/api/attendance/shifts/:id","type":0,"val":"shifts","end":""},{"old":"/api/attendance/shifts/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['attendances.update_shift']['types'],
  },
  'attendances.delete_shift': {
    methods: ["DELETE"],
    pattern: '/api/attendance/shifts/:id',
    tokens: [{"old":"/api/attendance/shifts/:id","type":0,"val":"api","end":""},{"old":"/api/attendance/shifts/:id","type":0,"val":"attendance","end":""},{"old":"/api/attendance/shifts/:id","type":0,"val":"shifts","end":""},{"old":"/api/attendance/shifts/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['attendances.delete_shift']['types'],
  },
  'regularizations.index': {
    methods: ["GET","HEAD"],
    pattern: '/api/regularizations',
    tokens: [{"old":"/api/regularizations","type":0,"val":"api","end":""},{"old":"/api/regularizations","type":0,"val":"regularizations","end":""}],
    types: placeholder as Registry['regularizations.index']['types'],
  },
  'regularizations.store': {
    methods: ["POST"],
    pattern: '/api/regularizations',
    tokens: [{"old":"/api/regularizations","type":0,"val":"api","end":""},{"old":"/api/regularizations","type":0,"val":"regularizations","end":""}],
    types: placeholder as Registry['regularizations.store']['types'],
  },
  'regularizations.update': {
    methods: ["PUT"],
    pattern: '/api/regularizations/:id',
    tokens: [{"old":"/api/regularizations/:id","type":0,"val":"api","end":""},{"old":"/api/regularizations/:id","type":0,"val":"regularizations","end":""},{"old":"/api/regularizations/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['regularizations.update']['types'],
  },
  'tracking.update': {
    methods: ["POST"],
    pattern: '/api/tracking/update',
    tokens: [{"old":"/api/tracking/update","type":0,"val":"api","end":""},{"old":"/api/tracking/update","type":0,"val":"tracking","end":""},{"old":"/api/tracking/update","type":0,"val":"update","end":""}],
    types: placeholder as Registry['tracking.update']['types'],
  },
  'tracking.history': {
    methods: ["GET","HEAD"],
    pattern: '/api/tracking/history',
    tokens: [{"old":"/api/tracking/history","type":0,"val":"api","end":""},{"old":"/api/tracking/history","type":0,"val":"tracking","end":""},{"old":"/api/tracking/history","type":0,"val":"history","end":""}],
    types: placeholder as Registry['tracking.history']['types'],
  },
  'leaves.index': {
    methods: ["GET","HEAD"],
    pattern: '/api/leaves',
    tokens: [{"old":"/api/leaves","type":0,"val":"api","end":""},{"old":"/api/leaves","type":0,"val":"leaves","end":""}],
    types: placeholder as Registry['leaves.index']['types'],
  },
  'leaves.get_types': {
    methods: ["GET","HEAD"],
    pattern: '/api/leaves/types',
    tokens: [{"old":"/api/leaves/types","type":0,"val":"api","end":""},{"old":"/api/leaves/types","type":0,"val":"leaves","end":""},{"old":"/api/leaves/types","type":0,"val":"types","end":""}],
    types: placeholder as Registry['leaves.get_types']['types'],
  },
  'leaves.create_type': {
    methods: ["POST"],
    pattern: '/api/leaves/types',
    tokens: [{"old":"/api/leaves/types","type":0,"val":"api","end":""},{"old":"/api/leaves/types","type":0,"val":"leaves","end":""},{"old":"/api/leaves/types","type":0,"val":"types","end":""}],
    types: placeholder as Registry['leaves.create_type']['types'],
  },
  'leaves.update_type': {
    methods: ["PUT"],
    pattern: '/api/leaves/types/:id',
    tokens: [{"old":"/api/leaves/types/:id","type":0,"val":"api","end":""},{"old":"/api/leaves/types/:id","type":0,"val":"leaves","end":""},{"old":"/api/leaves/types/:id","type":0,"val":"types","end":""},{"old":"/api/leaves/types/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['leaves.update_type']['types'],
  },
  'leaves.destroy_type': {
    methods: ["DELETE"],
    pattern: '/api/leaves/types/:id',
    tokens: [{"old":"/api/leaves/types/:id","type":0,"val":"api","end":""},{"old":"/api/leaves/types/:id","type":0,"val":"leaves","end":""},{"old":"/api/leaves/types/:id","type":0,"val":"types","end":""},{"old":"/api/leaves/types/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['leaves.destroy_type']['types'],
  },
  'leaves.store': {
    methods: ["POST"],
    pattern: '/api/leaves',
    tokens: [{"old":"/api/leaves","type":0,"val":"api","end":""},{"old":"/api/leaves","type":0,"val":"leaves","end":""}],
    types: placeholder as Registry['leaves.store']['types'],
  },
  'leaves.update_status': {
    methods: ["PUT"],
    pattern: '/api/leaves/:id/status',
    tokens: [{"old":"/api/leaves/:id/status","type":0,"val":"api","end":""},{"old":"/api/leaves/:id/status","type":0,"val":"leaves","end":""},{"old":"/api/leaves/:id/status","type":1,"val":"id","end":""},{"old":"/api/leaves/:id/status","type":0,"val":"status","end":""}],
    types: placeholder as Registry['leaves.update_status']['types'],
  },
  'leave_types_alias': {
    methods: ["GET","HEAD"],
    pattern: '/api/leave-types',
    tokens: [{"old":"/api/leave-types","type":0,"val":"api","end":""},{"old":"/api/leave-types","type":0,"val":"leave-types","end":""}],
    types: placeholder as Registry['leave_types_alias']['types'],
  },
  'payrolls.index': {
    methods: ["GET","HEAD"],
    pattern: '/api/payroll',
    tokens: [{"old":"/api/payroll","type":0,"val":"api","end":""},{"old":"/api/payroll","type":0,"val":"payroll","end":""}],
    types: placeholder as Registry['payrolls.index']['types'],
  },
  'payrolls.store': {
    methods: ["POST"],
    pattern: '/api/payroll',
    tokens: [{"old":"/api/payroll","type":0,"val":"api","end":""},{"old":"/api/payroll","type":0,"val":"payroll","end":""}],
    types: placeholder as Registry['payrolls.store']['types'],
  },
  'projects.index': {
    methods: ["GET","HEAD"],
    pattern: '/api/projects',
    tokens: [{"old":"/api/projects","type":0,"val":"api","end":""},{"old":"/api/projects","type":0,"val":"projects","end":""}],
    types: placeholder as Registry['projects.index']['types'],
  },
  'projects.store': {
    methods: ["POST"],
    pattern: '/api/projects',
    tokens: [{"old":"/api/projects","type":0,"val":"api","end":""},{"old":"/api/projects","type":0,"val":"projects","end":""}],
    types: placeholder as Registry['projects.store']['types'],
  },
  'projects.tasks': {
    methods: ["GET","HEAD"],
    pattern: '/api/projects/:id/tasks',
    tokens: [{"old":"/api/projects/:id/tasks","type":0,"val":"api","end":""},{"old":"/api/projects/:id/tasks","type":0,"val":"projects","end":""},{"old":"/api/projects/:id/tasks","type":1,"val":"id","end":""},{"old":"/api/projects/:id/tasks","type":0,"val":"tasks","end":""}],
    types: placeholder as Registry['projects.tasks']['types'],
  },
  'projects.store_task': {
    methods: ["POST"],
    pattern: '/api/projects/:id/tasks',
    tokens: [{"old":"/api/projects/:id/tasks","type":0,"val":"api","end":""},{"old":"/api/projects/:id/tasks","type":0,"val":"projects","end":""},{"old":"/api/projects/:id/tasks","type":1,"val":"id","end":""},{"old":"/api/projects/:id/tasks","type":0,"val":"tasks","end":""}],
    types: placeholder as Registry['projects.store_task']['types'],
  },
  'announcements.index': {
    methods: ["GET","HEAD"],
    pattern: '/api/announcements',
    tokens: [{"old":"/api/announcements","type":0,"val":"api","end":""},{"old":"/api/announcements","type":0,"val":"announcements","end":""}],
    types: placeholder as Registry['announcements.index']['types'],
  },
  'announcements.store': {
    methods: ["POST"],
    pattern: '/api/announcements',
    tokens: [{"old":"/api/announcements","type":0,"val":"api","end":""},{"old":"/api/announcements","type":0,"val":"announcements","end":""}],
    types: placeholder as Registry['announcements.store']['types'],
  },
  'expenses.index': {
    methods: ["GET","HEAD"],
    pattern: '/api/expenses',
    tokens: [{"old":"/api/expenses","type":0,"val":"api","end":""},{"old":"/api/expenses","type":0,"val":"expenses","end":""}],
    types: placeholder as Registry['expenses.index']['types'],
  },
  'expenses.store': {
    methods: ["POST"],
    pattern: '/api/expenses',
    tokens: [{"old":"/api/expenses","type":0,"val":"api","end":""},{"old":"/api/expenses","type":0,"val":"expenses","end":""}],
    types: placeholder as Registry['expenses.store']['types'],
  },
  'expenses.update_status': {
    methods: ["PUT"],
    pattern: '/api/expenses/:id/status',
    tokens: [{"old":"/api/expenses/:id/status","type":0,"val":"api","end":""},{"old":"/api/expenses/:id/status","type":0,"val":"expenses","end":""},{"old":"/api/expenses/:id/status","type":1,"val":"id","end":""},{"old":"/api/expenses/:id/status","type":0,"val":"status","end":""}],
    types: placeholder as Registry['expenses.update_status']['types'],
  },
  'timesheets.index': {
    methods: ["GET","HEAD"],
    pattern: '/api/timesheets',
    tokens: [{"old":"/api/timesheets","type":0,"val":"api","end":""},{"old":"/api/timesheets","type":0,"val":"timesheets","end":""}],
    types: placeholder as Registry['timesheets.index']['types'],
  },
  'timesheets.store': {
    methods: ["POST"],
    pattern: '/api/timesheets',
    tokens: [{"old":"/api/timesheets","type":0,"val":"api","end":""},{"old":"/api/timesheets","type":0,"val":"timesheets","end":""}],
    types: placeholder as Registry['timesheets.store']['types'],
  },
  'visit_management.dashboard': {
    methods: ["GET","HEAD"],
    pattern: '/api/visits/dashboard',
    tokens: [{"old":"/api/visits/dashboard","type":0,"val":"api","end":""},{"old":"/api/visits/dashboard","type":0,"val":"visits","end":""},{"old":"/api/visits/dashboard","type":0,"val":"dashboard","end":""}],
    types: placeholder as Registry['visit_management.dashboard']['types'],
  },
  'visit_management.references': {
    methods: ["GET","HEAD"],
    pattern: '/api/visits/references',
    tokens: [{"old":"/api/visits/references","type":0,"val":"api","end":""},{"old":"/api/visits/references","type":0,"val":"visits","end":""},{"old":"/api/visits/references","type":0,"val":"references","end":""}],
    types: placeholder as Registry['visit_management.references']['types'],
  },
  'visit_management.reports': {
    methods: ["GET","HEAD"],
    pattern: '/api/visits/reports',
    tokens: [{"old":"/api/visits/reports","type":0,"val":"api","end":""},{"old":"/api/visits/reports","type":0,"val":"visits","end":""},{"old":"/api/visits/reports","type":0,"val":"reports","end":""}],
    types: placeholder as Registry['visit_management.reports']['types'],
  },
  'visit_management.export_reports': {
    methods: ["GET","HEAD"],
    pattern: '/api/visits/reports/export',
    tokens: [{"old":"/api/visits/reports/export","type":0,"val":"api","end":""},{"old":"/api/visits/reports/export","type":0,"val":"visits","end":""},{"old":"/api/visits/reports/export","type":0,"val":"reports","end":""},{"old":"/api/visits/reports/export","type":0,"val":"export","end":""}],
    types: placeholder as Registry['visit_management.export_reports']['types'],
  },
  'visit_management.list_clients': {
    methods: ["GET","HEAD"],
    pattern: '/api/visits/clients',
    tokens: [{"old":"/api/visits/clients","type":0,"val":"api","end":""},{"old":"/api/visits/clients","type":0,"val":"visits","end":""},{"old":"/api/visits/clients","type":0,"val":"clients","end":""}],
    types: placeholder as Registry['visit_management.list_clients']['types'],
  },
  'visit_management.create_client': {
    methods: ["POST"],
    pattern: '/api/visits/clients',
    tokens: [{"old":"/api/visits/clients","type":0,"val":"api","end":""},{"old":"/api/visits/clients","type":0,"val":"visits","end":""},{"old":"/api/visits/clients","type":0,"val":"clients","end":""}],
    types: placeholder as Registry['visit_management.create_client']['types'],
  },
  'visit_management.update_client': {
    methods: ["PUT"],
    pattern: '/api/visits/clients/:id',
    tokens: [{"old":"/api/visits/clients/:id","type":0,"val":"api","end":""},{"old":"/api/visits/clients/:id","type":0,"val":"visits","end":""},{"old":"/api/visits/clients/:id","type":0,"val":"clients","end":""},{"old":"/api/visits/clients/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['visit_management.update_client']['types'],
  },
  'visit_management.list_visitors': {
    methods: ["GET","HEAD"],
    pattern: '/api/visits/visitors',
    tokens: [{"old":"/api/visits/visitors","type":0,"val":"api","end":""},{"old":"/api/visits/visitors","type":0,"val":"visits","end":""},{"old":"/api/visits/visitors","type":0,"val":"visitors","end":""}],
    types: placeholder as Registry['visit_management.list_visitors']['types'],
  },
  'visit_management.create_visitor': {
    methods: ["POST"],
    pattern: '/api/visits/visitors',
    tokens: [{"old":"/api/visits/visitors","type":0,"val":"api","end":""},{"old":"/api/visits/visitors","type":0,"val":"visits","end":""},{"old":"/api/visits/visitors","type":0,"val":"visitors","end":""}],
    types: placeholder as Registry['visit_management.create_visitor']['types'],
  },
  'visit_management.update_visitor': {
    methods: ["PUT"],
    pattern: '/api/visits/visitors/:id',
    tokens: [{"old":"/api/visits/visitors/:id","type":0,"val":"api","end":""},{"old":"/api/visits/visitors/:id","type":0,"val":"visits","end":""},{"old":"/api/visits/visitors/:id","type":0,"val":"visitors","end":""},{"old":"/api/visits/visitors/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['visit_management.update_visitor']['types'],
  },
  'visit_management.index': {
    methods: ["GET","HEAD"],
    pattern: '/api/visits',
    tokens: [{"old":"/api/visits","type":0,"val":"api","end":""},{"old":"/api/visits","type":0,"val":"visits","end":""}],
    types: placeholder as Registry['visit_management.index']['types'],
  },
  'visit_management.store': {
    methods: ["POST"],
    pattern: '/api/visits',
    tokens: [{"old":"/api/visits","type":0,"val":"api","end":""},{"old":"/api/visits","type":0,"val":"visits","end":""}],
    types: placeholder as Registry['visit_management.store']['types'],
  },
  'visit_management.show': {
    methods: ["GET","HEAD"],
    pattern: '/api/visits/:id',
    tokens: [{"old":"/api/visits/:id","type":0,"val":"api","end":""},{"old":"/api/visits/:id","type":0,"val":"visits","end":""},{"old":"/api/visits/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['visit_management.show']['types'],
  },
  'visit_management.update': {
    methods: ["PUT"],
    pattern: '/api/visits/:id',
    tokens: [{"old":"/api/visits/:id","type":0,"val":"api","end":""},{"old":"/api/visits/:id","type":0,"val":"visits","end":""},{"old":"/api/visits/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['visit_management.update']['types'],
  },
  'visit_management.review': {
    methods: ["POST"],
    pattern: '/api/visits/:id/review',
    tokens: [{"old":"/api/visits/:id/review","type":0,"val":"api","end":""},{"old":"/api/visits/:id/review","type":0,"val":"visits","end":""},{"old":"/api/visits/:id/review","type":1,"val":"id","end":""},{"old":"/api/visits/:id/review","type":0,"val":"review","end":""}],
    types: placeholder as Registry['visit_management.review']['types'],
  },
  'visit_management.check_in': {
    methods: ["POST"],
    pattern: '/api/visits/:id/check-in',
    tokens: [{"old":"/api/visits/:id/check-in","type":0,"val":"api","end":""},{"old":"/api/visits/:id/check-in","type":0,"val":"visits","end":""},{"old":"/api/visits/:id/check-in","type":1,"val":"id","end":""},{"old":"/api/visits/:id/check-in","type":0,"val":"check-in","end":""}],
    types: placeholder as Registry['visit_management.check_in']['types'],
  },
  'visit_management.check_out': {
    methods: ["POST"],
    pattern: '/api/visits/:id/check-out',
    tokens: [{"old":"/api/visits/:id/check-out","type":0,"val":"api","end":""},{"old":"/api/visits/:id/check-out","type":0,"val":"visits","end":""},{"old":"/api/visits/:id/check-out","type":1,"val":"id","end":""},{"old":"/api/visits/:id/check-out","type":0,"val":"check-out","end":""}],
    types: placeholder as Registry['visit_management.check_out']['types'],
  },
  'visit_management.add_note': {
    methods: ["POST"],
    pattern: '/api/visits/:id/notes',
    tokens: [{"old":"/api/visits/:id/notes","type":0,"val":"api","end":""},{"old":"/api/visits/:id/notes","type":0,"val":"visits","end":""},{"old":"/api/visits/:id/notes","type":1,"val":"id","end":""},{"old":"/api/visits/:id/notes","type":0,"val":"notes","end":""}],
    types: placeholder as Registry['visit_management.add_note']['types'],
  },
  'visit_management.add_follow_up': {
    methods: ["POST"],
    pattern: '/api/visits/:id/follow-ups',
    tokens: [{"old":"/api/visits/:id/follow-ups","type":0,"val":"api","end":""},{"old":"/api/visits/:id/follow-ups","type":0,"val":"visits","end":""},{"old":"/api/visits/:id/follow-ups","type":1,"val":"id","end":""},{"old":"/api/visits/:id/follow-ups","type":0,"val":"follow-ups","end":""}],
    types: placeholder as Registry['visit_management.add_follow_up']['types'],
  },
  'visit_management.update_follow_up': {
    methods: ["PUT"],
    pattern: '/api/visits/follow-ups/:followUpId',
    tokens: [{"old":"/api/visits/follow-ups/:followUpId","type":0,"val":"api","end":""},{"old":"/api/visits/follow-ups/:followUpId","type":0,"val":"visits","end":""},{"old":"/api/visits/follow-ups/:followUpId","type":0,"val":"follow-ups","end":""},{"old":"/api/visits/follow-ups/:followUpId","type":1,"val":"followUpId","end":""}],
    types: placeholder as Registry['visit_management.update_follow_up']['types'],
  },
  'notifications.index': {
    methods: ["GET","HEAD"],
    pattern: '/api/notifications',
    tokens: [{"old":"/api/notifications","type":0,"val":"api","end":""},{"old":"/api/notifications","type":0,"val":"notifications","end":""}],
    types: placeholder as Registry['notifications.index']['types'],
  },
  'notifications.mark_as_read': {
    methods: ["PATCH"],
    pattern: '/api/notifications/:id/read',
    tokens: [{"old":"/api/notifications/:id/read","type":0,"val":"api","end":""},{"old":"/api/notifications/:id/read","type":0,"val":"notifications","end":""},{"old":"/api/notifications/:id/read","type":1,"val":"id","end":""},{"old":"/api/notifications/:id/read","type":0,"val":"read","end":""}],
    types: placeholder as Registry['notifications.mark_as_read']['types'],
  },
  'notifications.mark_all_as_read': {
    methods: ["POST"],
    pattern: '/api/notifications/read-all',
    tokens: [{"old":"/api/notifications/read-all","type":0,"val":"api","end":""},{"old":"/api/notifications/read-all","type":0,"val":"notifications","end":""},{"old":"/api/notifications/read-all","type":0,"val":"read-all","end":""}],
    types: placeholder as Registry['notifications.mark_all_as_read']['types'],
  },
  'notifications.destroy': {
    methods: ["DELETE"],
    pattern: '/api/notifications/:id',
    tokens: [{"old":"/api/notifications/:id","type":0,"val":"api","end":""},{"old":"/api/notifications/:id","type":0,"val":"notifications","end":""},{"old":"/api/notifications/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['notifications.destroy']['types'],
  },
  'employee_self_service.dashboard': {
    methods: ["GET","HEAD"],
    pattern: '/api/ess/dashboard',
    tokens: [{"old":"/api/ess/dashboard","type":0,"val":"api","end":""},{"old":"/api/ess/dashboard","type":0,"val":"ess","end":""},{"old":"/api/ess/dashboard","type":0,"val":"dashboard","end":""}],
    types: placeholder as Registry['employee_self_service.dashboard']['types'],
  },
  'employee_self_service.list_requests': {
    methods: ["GET","HEAD"],
    pattern: '/api/ess/requests',
    tokens: [{"old":"/api/ess/requests","type":0,"val":"api","end":""},{"old":"/api/ess/requests","type":0,"val":"ess","end":""},{"old":"/api/ess/requests","type":0,"val":"requests","end":""}],
    types: placeholder as Registry['employee_self_service.list_requests']['types'],
  },
  'employee_self_service.create_request': {
    methods: ["POST"],
    pattern: '/api/ess/requests',
    tokens: [{"old":"/api/ess/requests","type":0,"val":"api","end":""},{"old":"/api/ess/requests","type":0,"val":"ess","end":""},{"old":"/api/ess/requests","type":0,"val":"requests","end":""}],
    types: placeholder as Registry['employee_self_service.create_request']['types'],
  },
  'employee_self_service.cancel_request': {
    methods: ["POST"],
    pattern: '/api/ess/requests/:id/cancel',
    tokens: [{"old":"/api/ess/requests/:id/cancel","type":0,"val":"api","end":""},{"old":"/api/ess/requests/:id/cancel","type":0,"val":"ess","end":""},{"old":"/api/ess/requests/:id/cancel","type":0,"val":"requests","end":""},{"old":"/api/ess/requests/:id/cancel","type":1,"val":"id","end":""},{"old":"/api/ess/requests/:id/cancel","type":0,"val":"cancel","end":""}],
    types: placeholder as Registry['employee_self_service.cancel_request']['types'],
  },
  'employee_self_service.profile_audit': {
    methods: ["GET","HEAD"],
    pattern: '/api/ess/profile-audit',
    tokens: [{"old":"/api/ess/profile-audit","type":0,"val":"api","end":""},{"old":"/api/ess/profile-audit","type":0,"val":"ess","end":""},{"old":"/api/ess/profile-audit","type":0,"val":"profile-audit","end":""}],
    types: placeholder as Registry['employee_self_service.profile_audit']['types'],
  },
  'employee_self_service.login_activity': {
    methods: ["GET","HEAD"],
    pattern: '/api/ess/login-activity',
    tokens: [{"old":"/api/ess/login-activity","type":0,"val":"api","end":""},{"old":"/api/ess/login-activity","type":0,"val":"ess","end":""},{"old":"/api/ess/login-activity","type":0,"val":"login-activity","end":""}],
    types: placeholder as Registry['employee_self_service.login_activity']['types'],
  },
  'employee_self_service.change_password': {
    methods: ["POST"],
    pattern: '/api/ess/change-password',
    tokens: [{"old":"/api/ess/change-password","type":0,"val":"api","end":""},{"old":"/api/ess/change-password","type":0,"val":"ess","end":""},{"old":"/api/ess/change-password","type":0,"val":"change-password","end":""}],
    types: placeholder as Registry['employee_self_service.change_password']['types'],
  },
  'audit_logs.index': {
    methods: ["GET","HEAD"],
    pattern: '/api/audit-logs',
    tokens: [{"old":"/api/audit-logs","type":0,"val":"api","end":""},{"old":"/api/audit-logs","type":0,"val":"audit-logs","end":""}],
    types: placeholder as Registry['audit_logs.index']['types'],
  },
  'audit_logs.store': {
    methods: ["POST"],
    pattern: '/api/audit-logs',
    tokens: [{"old":"/api/audit-logs","type":0,"val":"api","end":""},{"old":"/api/audit-logs","type":0,"val":"audit-logs","end":""}],
    types: placeholder as Registry['audit_logs.store']['types'],
  },
  'audit_logs.get_modules': {
    methods: ["GET","HEAD"],
    pattern: '/api/audit-logs/modules',
    tokens: [{"old":"/api/audit-logs/modules","type":0,"val":"api","end":""},{"old":"/api/audit-logs/modules","type":0,"val":"audit-logs","end":""},{"old":"/api/audit-logs/modules","type":0,"val":"modules","end":""}],
    types: placeholder as Registry['audit_logs.get_modules']['types'],
  },
  'audit_logs.get_actions': {
    methods: ["GET","HEAD"],
    pattern: '/api/audit-logs/actions',
    tokens: [{"old":"/api/audit-logs/actions","type":0,"val":"api","end":""},{"old":"/api/audit-logs/actions","type":0,"val":"audit-logs","end":""},{"old":"/api/audit-logs/actions","type":0,"val":"actions","end":""}],
    types: placeholder as Registry['audit_logs.get_actions']['types'],
  },
  'audit_logs.export': {
    methods: ["GET","HEAD"],
    pattern: '/api/audit-logs/export',
    tokens: [{"old":"/api/audit-logs/export","type":0,"val":"api","end":""},{"old":"/api/audit-logs/export","type":0,"val":"audit-logs","end":""},{"old":"/api/audit-logs/export","type":0,"val":"export","end":""}],
    types: placeholder as Registry['audit_logs.export']['types'],
  },
  'audit_logs.show': {
    methods: ["GET","HEAD"],
    pattern: '/api/audit-logs/:id',
    tokens: [{"old":"/api/audit-logs/:id","type":0,"val":"api","end":""},{"old":"/api/audit-logs/:id","type":0,"val":"audit-logs","end":""},{"old":"/api/audit-logs/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['audit_logs.show']['types'],
  },
  'documents.index': {
    methods: ["GET","HEAD"],
    pattern: '/api/documents',
    tokens: [{"old":"/api/documents","type":0,"val":"api","end":""},{"old":"/api/documents","type":0,"val":"documents","end":""}],
    types: placeholder as Registry['documents.index']['types'],
  },
  'documents.store': {
    methods: ["POST"],
    pattern: '/api/documents',
    tokens: [{"old":"/api/documents","type":0,"val":"api","end":""},{"old":"/api/documents","type":0,"val":"documents","end":""}],
    types: placeholder as Registry['documents.store']['types'],
  },
  'documents.download': {
    methods: ["GET","HEAD"],
    pattern: '/api/documents/:id/download',
    tokens: [{"old":"/api/documents/:id/download","type":0,"val":"api","end":""},{"old":"/api/documents/:id/download","type":0,"val":"documents","end":""},{"old":"/api/documents/:id/download","type":1,"val":"id","end":""},{"old":"/api/documents/:id/download","type":0,"val":"download","end":""}],
    types: placeholder as Registry['documents.download']['types'],
  },
  'documents.destroy': {
    methods: ["DELETE"],
    pattern: '/api/documents/:id',
    tokens: [{"old":"/api/documents/:id","type":0,"val":"api","end":""},{"old":"/api/documents/:id","type":0,"val":"documents","end":""},{"old":"/api/documents/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['documents.destroy']['types'],
  },
  'roles.index': {
    methods: ["GET","HEAD"],
    pattern: '/api/roles',
    tokens: [{"old":"/api/roles","type":0,"val":"api","end":""},{"old":"/api/roles","type":0,"val":"roles","end":""}],
    types: placeholder as Registry['roles.index']['types'],
  },
  'roles.store': {
    methods: ["POST"],
    pattern: '/api/roles',
    tokens: [{"old":"/api/roles","type":0,"val":"api","end":""},{"old":"/api/roles","type":0,"val":"roles","end":""}],
    types: placeholder as Registry['roles.store']['types'],
  },
  'roles.show': {
    methods: ["GET","HEAD"],
    pattern: '/api/roles/:id',
    tokens: [{"old":"/api/roles/:id","type":0,"val":"api","end":""},{"old":"/api/roles/:id","type":0,"val":"roles","end":""},{"old":"/api/roles/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['roles.show']['types'],
  },
  'roles.update': {
    methods: ["PUT"],
    pattern: '/api/roles/:id',
    tokens: [{"old":"/api/roles/:id","type":0,"val":"api","end":""},{"old":"/api/roles/:id","type":0,"val":"roles","end":""},{"old":"/api/roles/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['roles.update']['types'],
  },
  'roles.get_permissions': {
    methods: ["GET","HEAD"],
    pattern: '/api/roles/permissions',
    tokens: [{"old":"/api/roles/permissions","type":0,"val":"api","end":""},{"old":"/api/roles/permissions","type":0,"val":"roles","end":""},{"old":"/api/roles/permissions","type":0,"val":"permissions","end":""}],
    types: placeholder as Registry['roles.get_permissions']['types'],
  },
  'roles.destroy': {
    methods: ["DELETE"],
    pattern: '/api/roles/:id',
    tokens: [{"old":"/api/roles/:id","type":0,"val":"api","end":""},{"old":"/api/roles/:id","type":0,"val":"roles","end":""},{"old":"/api/roles/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['roles.destroy']['types'],
  },
  'employee_experiences.index': {
    methods: ["GET","HEAD"],
    pattern: '/api/experiences',
    tokens: [{"old":"/api/experiences","type":0,"val":"api","end":""},{"old":"/api/experiences","type":0,"val":"experiences","end":""}],
    types: placeholder as Registry['employee_experiences.index']['types'],
  },
  'employee_experiences.store': {
    methods: ["POST"],
    pattern: '/api/experiences',
    tokens: [{"old":"/api/experiences","type":0,"val":"api","end":""},{"old":"/api/experiences","type":0,"val":"experiences","end":""}],
    types: placeholder as Registry['employee_experiences.store']['types'],
  },
  'employee_experiences.update': {
    methods: ["PUT"],
    pattern: '/api/experiences/:id',
    tokens: [{"old":"/api/experiences/:id","type":0,"val":"api","end":""},{"old":"/api/experiences/:id","type":0,"val":"experiences","end":""},{"old":"/api/experiences/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['employee_experiences.update']['types'],
  },
  'employee_experiences.destroy': {
    methods: ["DELETE"],
    pattern: '/api/experiences/:id',
    tokens: [{"old":"/api/experiences/:id","type":0,"val":"api","end":""},{"old":"/api/experiences/:id","type":0,"val":"experiences","end":""},{"old":"/api/experiences/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['employee_experiences.destroy']['types'],
  },
  'employee_educations.index': {
    methods: ["GET","HEAD"],
    pattern: '/api/education',
    tokens: [{"old":"/api/education","type":0,"val":"api","end":""},{"old":"/api/education","type":0,"val":"education","end":""}],
    types: placeholder as Registry['employee_educations.index']['types'],
  },
  'employee_educations.store': {
    methods: ["POST"],
    pattern: '/api/education',
    tokens: [{"old":"/api/education","type":0,"val":"api","end":""},{"old":"/api/education","type":0,"val":"education","end":""}],
    types: placeholder as Registry['employee_educations.store']['types'],
  },
  'employee_educations.update': {
    methods: ["PUT"],
    pattern: '/api/education/:id',
    tokens: [{"old":"/api/education/:id","type":0,"val":"api","end":""},{"old":"/api/education/:id","type":0,"val":"education","end":""},{"old":"/api/education/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['employee_educations.update']['types'],
  },
  'employee_educations.destroy': {
    methods: ["DELETE"],
    pattern: '/api/education/:id',
    tokens: [{"old":"/api/education/:id","type":0,"val":"api","end":""},{"old":"/api/education/:id","type":0,"val":"education","end":""},{"old":"/api/education/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['employee_educations.destroy']['types'],
  },
  'face_recognition.register': {
    methods: ["POST"],
    pattern: '/api/face/register',
    tokens: [{"old":"/api/face/register","type":0,"val":"api","end":""},{"old":"/api/face/register","type":0,"val":"face","end":""},{"old":"/api/face/register","type":0,"val":"register","end":""}],
    types: placeholder as Registry['face_recognition.register']['types'],
  },
  'face_recognition.verify': {
    methods: ["POST"],
    pattern: '/api/face/verify',
    tokens: [{"old":"/api/face/verify","type":0,"val":"api","end":""},{"old":"/api/face/verify","type":0,"val":"face","end":""},{"old":"/api/face/verify","type":0,"val":"verify","end":""}],
    types: placeholder as Registry['face_recognition.verify']['types'],
  },
  'face_recognition.status': {
    methods: ["GET","HEAD"],
    pattern: '/api/face/status/:id',
    tokens: [{"old":"/api/face/status/:id","type":0,"val":"api","end":""},{"old":"/api/face/status/:id","type":0,"val":"face","end":""},{"old":"/api/face/status/:id","type":0,"val":"status","end":""},{"old":"/api/face/status/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['face_recognition.status']['types'],
  },
  'face_recognition.delete': {
    methods: ["DELETE"],
    pattern: '/api/face/:id',
    tokens: [{"old":"/api/face/:id","type":0,"val":"api","end":""},{"old":"/api/face/:id","type":0,"val":"face","end":""},{"old":"/api/face/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['face_recognition.delete']['types'],
  },
  'employee_invitations.invite': {
    methods: ["POST"],
    pattern: '/api/employees/invite',
    tokens: [{"old":"/api/employees/invite","type":0,"val":"api","end":""},{"old":"/api/employees/invite","type":0,"val":"employees","end":""},{"old":"/api/employees/invite","type":0,"val":"invite","end":""}],
    types: placeholder as Registry['employee_invitations.invite']['types'],
  },
  'employee_invitations.list': {
    methods: ["GET","HEAD"],
    pattern: '/api/employees/invitations',
    tokens: [{"old":"/api/employees/invitations","type":0,"val":"api","end":""},{"old":"/api/employees/invitations","type":0,"val":"employees","end":""},{"old":"/api/employees/invitations","type":0,"val":"invitations","end":""}],
    types: placeholder as Registry['employee_invitations.list']['types'],
  },
  'employee_invitations.revoke': {
    methods: ["POST"],
    pattern: '/api/employees/invitations/:id/revoke',
    tokens: [{"old":"/api/employees/invitations/:id/revoke","type":0,"val":"api","end":""},{"old":"/api/employees/invitations/:id/revoke","type":0,"val":"employees","end":""},{"old":"/api/employees/invitations/:id/revoke","type":0,"val":"invitations","end":""},{"old":"/api/employees/invitations/:id/revoke","type":1,"val":"id","end":""},{"old":"/api/employees/invitations/:id/revoke","type":0,"val":"revoke","end":""}],
    types: placeholder as Registry['employee_invitations.revoke']['types'],
  },
  'employee_invitations.resend': {
    methods: ["POST"],
    pattern: '/api/employees/invitations/:id/resend',
    tokens: [{"old":"/api/employees/invitations/:id/resend","type":0,"val":"api","end":""},{"old":"/api/employees/invitations/:id/resend","type":0,"val":"employees","end":""},{"old":"/api/employees/invitations/:id/resend","type":0,"val":"invitations","end":""},{"old":"/api/employees/invitations/:id/resend","type":1,"val":"id","end":""},{"old":"/api/employees/invitations/:id/resend","type":0,"val":"resend","end":""}],
    types: placeholder as Registry['employee_invitations.resend']['types'],
  },
  'employee_invitations.get_by_token': {
    methods: ["GET","HEAD"],
    pattern: '/api/invitations/:token',
    tokens: [{"old":"/api/invitations/:token","type":0,"val":"api","end":""},{"old":"/api/invitations/:token","type":0,"val":"invitations","end":""},{"old":"/api/invitations/:token","type":1,"val":"token","end":""}],
    types: placeholder as Registry['employee_invitations.get_by_token']['types'],
  },
  'employee_invitations.respond': {
    methods: ["POST"],
    pattern: '/api/invitations/:token/respond',
    tokens: [{"old":"/api/invitations/:token/respond","type":0,"val":"api","end":""},{"old":"/api/invitations/:token/respond","type":0,"val":"invitations","end":""},{"old":"/api/invitations/:token/respond","type":1,"val":"token","end":""},{"old":"/api/invitations/:token/respond","type":0,"val":"respond","end":""}],
    types: placeholder as Registry['employee_invitations.respond']['types'],
  },
  'leaves.get_balances': {
    methods: ["GET","HEAD"],
    pattern: '/api/leaves/balances',
    tokens: [{"old":"/api/leaves/balances","type":0,"val":"api","end":""},{"old":"/api/leaves/balances","type":0,"val":"leaves","end":""},{"old":"/api/leaves/balances","type":0,"val":"balances","end":""}],
    types: placeholder as Registry['leaves.get_balances']['types'],
  },
  'leaves.adjust_balance': {
    methods: ["POST"],
    pattern: '/api/leaves/balances/adjust',
    tokens: [{"old":"/api/leaves/balances/adjust","type":0,"val":"api","end":""},{"old":"/api/leaves/balances/adjust","type":0,"val":"leaves","end":""},{"old":"/api/leaves/balances/adjust","type":0,"val":"balances","end":""},{"old":"/api/leaves/balances/adjust","type":0,"val":"adjust","end":""}],
    types: placeholder as Registry['leaves.adjust_balance']['types'],
  },
  'reports.get_daily_report': {
    methods: ["GET","HEAD"],
    pattern: '/api/reports/daily',
    tokens: [{"old":"/api/reports/daily","type":0,"val":"api","end":""},{"old":"/api/reports/daily","type":0,"val":"reports","end":""},{"old":"/api/reports/daily","type":0,"val":"daily","end":""}],
    types: placeholder as Registry['reports.get_daily_report']['types'],
  },
  'reports.get_monthly_report': {
    methods: ["GET","HEAD"],
    pattern: '/api/reports/monthly',
    tokens: [{"old":"/api/reports/monthly","type":0,"val":"api","end":""},{"old":"/api/reports/monthly","type":0,"val":"reports","end":""},{"old":"/api/reports/monthly","type":0,"val":"monthly","end":""}],
    types: placeholder as Registry['reports.get_monthly_report']['types'],
  },
  'reports.get_attendance_report': {
    methods: ["GET","HEAD"],
    pattern: '/api/reports/attendance',
    tokens: [{"old":"/api/reports/attendance","type":0,"val":"api","end":""},{"old":"/api/reports/attendance","type":0,"val":"reports","end":""},{"old":"/api/reports/attendance","type":0,"val":"attendance","end":""}],
    types: placeholder as Registry['reports.get_attendance_report']['types'],
  },
  'reports.get_attendance_dashboard': {
    methods: ["GET","HEAD"],
    pattern: '/api/reports/attendance-dashboard',
    tokens: [{"old":"/api/reports/attendance-dashboard","type":0,"val":"api","end":""},{"old":"/api/reports/attendance-dashboard","type":0,"val":"reports","end":""},{"old":"/api/reports/attendance-dashboard","type":0,"val":"attendance-dashboard","end":""}],
    types: placeholder as Registry['reports.get_attendance_dashboard']['types'],
  },
  'reports.get_late_arrivals': {
    methods: ["GET","HEAD"],
    pattern: '/api/reports/late',
    tokens: [{"old":"/api/reports/late","type":0,"val":"api","end":""},{"old":"/api/reports/late","type":0,"val":"reports","end":""},{"old":"/api/reports/late","type":0,"val":"late","end":""}],
    types: placeholder as Registry['reports.get_late_arrivals']['types'],
  },
  'reports.get_absent_report': {
    methods: ["GET","HEAD"],
    pattern: '/api/reports/absent',
    tokens: [{"old":"/api/reports/absent","type":0,"val":"api","end":""},{"old":"/api/reports/absent","type":0,"val":"reports","end":""},{"old":"/api/reports/absent","type":0,"val":"absent","end":""}],
    types: placeholder as Registry['reports.get_absent_report']['types'],
  },
  'reports.get_summary': {
    methods: ["GET","HEAD"],
    pattern: '/api/reports/summary',
    tokens: [{"old":"/api/reports/summary","type":0,"val":"api","end":""},{"old":"/api/reports/summary","type":0,"val":"reports","end":""},{"old":"/api/reports/summary","type":0,"val":"summary","end":""}],
    types: placeholder as Registry['reports.get_summary']['types'],
  },
  'reports.get_weekly_attendance': {
    methods: ["GET","HEAD"],
    pattern: '/api/reports/weekly',
    tokens: [{"old":"/api/reports/weekly","type":0,"val":"api","end":""},{"old":"/api/reports/weekly","type":0,"val":"reports","end":""},{"old":"/api/reports/weekly","type":0,"val":"weekly","end":""}],
    types: placeholder as Registry['reports.get_weekly_attendance']['types'],
  },
  'reports.get_department_wise_attendance': {
    methods: ["GET","HEAD"],
    pattern: '/api/reports/by-department',
    tokens: [{"old":"/api/reports/by-department","type":0,"val":"api","end":""},{"old":"/api/reports/by-department","type":0,"val":"reports","end":""},{"old":"/api/reports/by-department","type":0,"val":"by-department","end":""}],
    types: placeholder as Registry['reports.get_department_wise_attendance']['types'],
  },
  'reports.export_excel': {
    methods: ["GET","HEAD"],
    pattern: '/api/reports/export/excel',
    tokens: [{"old":"/api/reports/export/excel","type":0,"val":"api","end":""},{"old":"/api/reports/export/excel","type":0,"val":"reports","end":""},{"old":"/api/reports/export/excel","type":0,"val":"export","end":""},{"old":"/api/reports/export/excel","type":0,"val":"excel","end":""}],
    types: placeholder as Registry['reports.export_excel']['types'],
  },
  'reports.export_pdf': {
    methods: ["GET","HEAD"],
    pattern: '/api/reports/export/pdf',
    tokens: [{"old":"/api/reports/export/pdf","type":0,"val":"api","end":""},{"old":"/api/reports/export/pdf","type":0,"val":"reports","end":""},{"old":"/api/reports/export/pdf","type":0,"val":"export","end":""},{"old":"/api/reports/export/pdf","type":0,"val":"pdf","end":""}],
    types: placeholder as Registry['reports.export_pdf']['types'],
  },
} as const satisfies Record<string, AdonisEndpoint>

export { routes }

export const registry = {
  routes,
  $tree: {} as ApiDefinition,
}

declare module '@tuyau/core/types' {
  export interface UserRegistry {
    routes: typeof routes
    $tree: ApiDefinition
  }
}
